### ISSUE TITLE
Range Operators

### ISSUE THREAD

**Issue by jkleiser** [wren-lang/wren#102]
I find the current wren range operators ".." and "..." not very intuitive. I suggest you replace these with the ones used by Swift, "..." (closed range operator) and "..<" (half-open range operator).
https://developer.apple.com/library/mac/documentation/Swift/Conceptual/Swift_Programming_Language/BasicOperators.html

**Comment by zeckalpha** [comment]
I agree these are not intuitive, but there is precedence in other languages for these, e.g. Ruby. I'm not sure the Swift operators are much better.

**Comment by munificent** [comment]
Yeah, this has come up before. See #53 by @skybrian.

I really like the way the current operators look, but I agree they aren't very intuitive. You basically just have to learn them. They have precedent if you come from Ruby (and less so Perl and Groovy), but that's it.

The `..<` is more explicit, but I find it really ugly. In particular, I expect to see a space between a `<` and its right operand, but that's not how you'd expect to style `..<`. To me, `1..<3`, `1 ..< 3` and `1..< 3` all look bad. It also seems to me like using `<` begs for other combinations like `>..` or `>..<`. While the squinting frog has a certain visual appeal, I really don't want to add a slew of operators.

An early incarnation of another language of mine used `to` and `until` (as methods) for these operations, like: `1.to(3)` and `1.until(3)` but I find that really verbose and ugly. Making them real operators like `1 to 3` and `1 until 3` is a little better, but still kind of weird and definitely painfully long.

I think `..` and `...` are the best compromise, but I'll leave this bug open for a while in case anyone can come up with some alternatives to consider.

**Comment by zeckalpha** [comment]
Even worse would be the mathematical notation:

[0, 3)
(0, 3)
[1, 20]
(1, 20]

**Comment by munificent** [comment]
Haha, oh god. That would be an ambiguity nightmare. :)

**Comment by skybrian** [comment]
Another possibility would be to keep one range operator and write out the other if it's less common:

1..3
1 until 3

But I'm not sure which one is used more in real programs.

**Comment by unc0** [comment]
Check out [gorillascript](http://ckknight.github.io/gorillascript/#loops). It uses `to`, `til` and `by` for ranges.

**Comment by zeckalpha** [comment]
Matlab / Julia (1-indexed) use `:`:
~~~
for j=1:4,
   j
end
~~~

Perhaps .. for including the end and : for excluding?

**Comment by munificent** [comment]
Yeah, GorillaScript is similar to what Magpie did. My intuition is that punctuation is a better fit than a reserved word. Reserved words as infix operators get really hard to read really quickly. You can end up with word soup.

I also worry that those can lead to unending requests for other infix words. Punctuation is nicely self-limiting in that anything beyond the familiar ones from math are pretty easy to rule out. (Of course, that exact problem is what got us to this bug to begin with...)

Julia's solution is neat, but I don't want to overload colon for that since it's so potentially useful for other things (map literals, named parameters, type annotations, records, etc.). Like [Larry Wall says](http://www.perl.com/pub/2001/04/02/wall.html), "Everybody wants the colon".

**Comment by munificent** [comment]
There's another problem with `..<` that I just realized while writing a reply on the mailing list: it doesn't work with backwards ranges. Right now, `5..2` will iterate *down*. It can even be used to do things like take a backwards slice of a list. But that doesn't make sense if you write it like: `5..<2`

**Comment by uvtc** [comment]
I've found an easy mnemonic: the range goes from the first number to the thing after two dots. If it's a number, great. If it's a dot (with a number following it), then if you squint, that dot can look a bit like the number that comes right before the one at the end. :)

**Comment by skybrian** [comment]
Perhaps it would be better to just have a single range operator?

  1..text.length
  0..text.length-1

Writing out "-1" is only one more character than "..." and it's certainly explicit.

If the last number or the range is a constant, you can just evaluate it and it's actually shorter:
  1...10 => 1..10-1 => 1..9

**Comment by zeckalpha** [comment]
:+1:

**Comment by munificent** [comment]
> Writing out "-1" is only one more character than "..."

Three more if you put spaces around the `-`. :)

`length - 1` is also not needed in most cases. Since we allow negative numbers to index from the end implicitly, you can usually just do:

```dart
someList[0..-1]
```

To refer to the whole list. Because of that, non-exclusive ranges aren't that common in practice, I don't think.

**Comment by RickGlimmer** [comment]
I personally prefer the range to be clear like 1..10-1 as the visual difference between 1..10 and 1...10 is not distinct enough.
Counting dots to find a subtle bug would be harder when using both the double and triple dots operators. As most ranges will be inclusive adding the -1 will draw extra attention reading the code, which i think is a good thing.

**Comment by skybrian** [comment]
Sure, that's what I was getting at. Non-exclusive ranges don't seem common enough to need their own operator, so perhaps just removing it would be easiest.

(Anyway, I've said quite enough about this tiny wart considering that I've barely used Wren, so I'll stop kibitzing now.)

**Comment by MarcoLizza** [comment]
Sorry for adding to this (already long) discussion... but since it's `Range` related, it seemed to fit the case.

It just occurred to me that, if I'm not wrong, at the moment the range operator does not permit to specify a step other than `1` (ascending and/or descending).

Would be nice to have something that initialize a different step value? That is
```
for (i in 1..100:1) {
  IO.print(i)
}
```
for a normal one-value stepped sequence, and
```
for (i in 1..100:2) {
  IO.print(i)
}
```
for a two-step on?

**Comment by zeckalpha** [comment]
Would that work for negatives, too? What about variables and expressions?

2...length:length/10

That could get hairy for minimal convenience.

**Comment by MarcoLizza** [comment]
> Would that work for negatives, too?

Yes. The sign can be inferred by comparing the starting and ending range limits.

> What about variables and expressions?

I don't think they would be a greater problem than now.

> That could get hairy for minimal convenience.

So which other simple and clean method we should use for a two-valued step?
```
var i = 0
while (i < 10) {
  // ...
  i = i + 1
}
```
Idiomatic, but more noisy...

**Comment by munificent** [comment]
> It just occurred to me that, if I'm not wrong, at the moment the range operator does not permit to specify a step other than 1 (ascending and/or descending).

This is true, but in practice I very rarely need this. I don't think it's useful enough to add dedicated syntax for it. If you don't want to use a `while` loop, you could also do:

```dart
for (i in 0...5) {
  // Use "i * 2"...
}
```

**Comment by MarcoLizza** [comment]
> This is true, but in practice I very rarely need this.

Agree. To be honest, iterations with step greater than one are uncommon.

They could be of more use when using them as a list-item selectors/subscriptors. In this case, however, a more general functor would be a better choice.
