### ISSUE TITLE
wren_core.h references IO.write (which is a Lua thing, not Wren thing)

### ISSUE THREAD

**Issue by eseidel** [wren-lang/wren#1039]
```
// There is one limitation, though. Methods written in C cannot call Wren ones.
// They can only be the top of the callstack, and immediately return. This
// makes it difficult to have primitive methods that rely on polymorphic
// behavior. For example, `IO.write` should call `toString` on its argument,
// including user-defined `toString` methods on user-defined classes.
```

Is that intentional?  I suspect that dates from an earlier version of Wren which named System to IO?  Not sure.  Or maybe it just assumes the reader knows Lua?

**Comment by joshgoebel** [comment]
Yes I think it's referring to `System.write` there.

**Comment by eseidel** [comment]
The message may still be dated however, since system.write is (presumably
intentionally to solve this?) implemented in wren_core.wren.

Donno. Regardless, thanks for the reply.

**Comment by joshgoebel** [comment]
I don't think the message is not-dated (just the symbol name)... it's talking about this very thing explicitly.  In core we'd *prefer* to call `toString` from C to follow the "as much C as possible" rule but we can't do that in this single case because re-entrancy could bite us - so it **must be** done on the Wren side instead.

Presumably in the future if this limitation was removed then this would be moved out of Wren and into the C side (that's how I read the comment).

**Comment by ChayimFriedman2** [comment]
`System.write()` was `IO.write()` in the past, renamed in 58e4d266487f9e9eb7fdec79582ab1ac80fbc7bb.
