### ISSUE TITLE
Question: Performance enhancement in the VM 

### ISSUE THREAD

**Issue by Gundolf68** [wren-lang/wren#1041]
The stack access in wren_vm.c currently runs like this:  
```C 
#define PUSH(value)  (*fiber->stackTop++ = value)
#define POP()        (*(--fiber->stackTop))
...
```
Couldn't things be made faster by keeping the stack pointer in a register?
Like this:
```C 
register Value* sp = fiber->stackTop;
...
#define PUSH(value)  (*sp++ = value)
#define POP()        (*(--sp))
...
```

**Comment by joshgoebel** [comment]
Just a note, if possible the compiler may already do this automatically.

**Comment by iSLC** [comment]
> Just a note, if possible the compiler may already do this automatically.

Not only it does this automatically, it completely ignores the `register` keyword. Some compilers may even generate warning messages on ussages of this keyword.

In c++ the keyword is completely [deprecated in newer standards](https://en.cppreference.com/w/cpp/keyword/register) . And I wouldn't be surprised if C would follow that practice.

So yeah, the `register` keyword is not something you have to worry these days. Due to advancements in compiler optimizations.
