### ISSUE TITLE
Is your language have an IDE for it?

### ISSUE THREAD

**Issue by 3oheicrw** [wren-lang/wren#1085]
Or any support to popular code editors to allow syntax highlighting and code completion?

**Comment by ruby0x1** [comment]
There's syntax highlighting and basic support for many editors, like vscode and such, but code completion is a work in progress due to how wren has the host (e.g the application that embeds it) make decisions about certain things, it's less easy to generalize. It's something we're actively working toward though.

**Comment by 3oheicrw** [comment]
@ruby0x1 You said there are syntax highlighting and basic support for many editors, but I can't find any except a WIP vscode extension (https://github.com/wren-lang/wren-vscode). If you can, please help with this. Thanks.

https://github.com/Alexey-T/CudaText/issues/4439
