### ISSUE TITLE
[RFC] Object.responds(_) method

### ISSUE THREAD

**Issue by clsource** [wren-lang/wren#1149]
In order to determine if a class implements  a given method.
Returns a Boolean value that indicates whether the receiver 
implements or inherits a method that can respond to a specified message.

```wren
// object.responds(method : String, arity: Num \\ 0)
Fn.new{}.responds("call") // true
123.responds("call", 0) // will look for the fullSignature call()
123.responds("call", 1) // will look for the fullSignature call(_)
123.responds("call", 2) // will look for the fullSignature call(_,_)
```

**POC**

- `wren_core.c`
```c
DEF_PRIMITIVE(object_respondsTo)
{
  Obj* obj = AS_OBJ(args[0]);
  ObjString* name = AS_STRING(args[1]);

  bool responds = false;

  for (int i = 0; i < obj->classObj->methods.count; i++)
  {
    Method* method = &obj->classObj->methods.data[i];
    if (strcmp(method->name, name) != -1) {
      responds = true;
      break;
    }
  }
  RETURN_BOOL(responds);
}
```

```c
// object.responds(method : String, arity : Num)
PRIMITIVE(vm->objectClass, "responds(_,_)", object_respondsTo);
```

- `wren_value.c`

```c
typedef struct
{
  MethodType type;
  const char* name;

  // The method function itself. The [type] determines which field of the union
  // is used.
  union
  {
    Primitive primitive;
    WrenForeignMethodFn foreign;
    ObjClosure* closure;
  } as;
} Method;
```

- `wren_compiler.c`
```c
// Declares a method in the enclosing class with [signature].
//
// Reports an error if a method with that signature is already declared.
// Returns the symbol for the method.
static int declareMethod(Compiler* compiler, Signature* signature,
                         const char* name, int length)
{
  int symbol = signatureSymbol(compiler, signature);
  
  // See if the class has already declared method with this signature.
  ClassInfo* classInfo = compiler->enclosingClass;
  IntBuffer* methods = classInfo->inStatic
      ? &classInfo->staticMethods : &classInfo->methods;
  for (int i = 0; i < methods->count; i++)
  {

   // Here store the fullSignature (name) of the method
   // in the method object   
   methods->data[i]->name = name;

    if (methods->data[i] == symbol)
    {
      const char* staticPrefix = classInfo->inStatic ? "static " : "";
      error(compiler, "Class %s already defines a %smethod '%s'.",
            &compiler->enclosingClass->name->value, staticPrefix, name);
      break;
    }
  }


  wrenIntBufferWrite(compiler->parser->vm, methods, symbol);
  return symbol;
}
```

**Comment by mhermier** [comment]
That API is broken, it should take a complete signature instead. The model
you propose, doesn't handle setters and subscript syntax.

**Comment by mhermier** [comment]
There are security concerns with a reflection API, but that's definitely
something we need to help us.

That said nothing forbids to try to call the function in a fiber, and
handle the error manually. Though, it would be more a band aid than
something I'll consider good practice...

**Comment by CrazyInfin8** [comment]
I don't know how complicated it would be but instead of doing:

>```wren
>// object.responds(method : String, arity: Num \\ 0)
>Fn.new{}.responds("call") // true
>123.responds("call", 0) // will look for the fullSignature call()
>123.responds("call", 1) // will look for the fullSignature call(_)
>123.responds("call", 2) // will look for the fullSignature call(_,_)
>```

maybe we should do something similar to using call handles by passing the full signature. Instead of `responds(method: string, arity: number)` we'd use `responds(signature: string)` (which looks like `responds("name", 3)` vs `responds("name(_,_,_)")`).

Another thing I was thinking of was whether this should be for every type or just the `Class` type (the type accessible from `Object.type`). The problem is that any field can be overloaded so `Object.responds` could have it's behavior changed (I guess the behavior of `Object.type` could also be overloaded but less methods on `Object` means less potential methods to overload). Though the small trade off for using a static method on `Class` is that we'd need extra information to determine whether or not we are querying a static method.

```wren
class A {
    construct new() {}
    getter {}
    setter=(x) {}
    method() {}
    static getter {}
    static setter=(x) {}
    static method() {}
}

var a = A.new()

// if each type has a `responds` method:
// not static
a.responds("getter")
a.responds("setter=(_)")
// static
A.responds("getter")
A.responds("setter=(_)")

// if `responds` method is method of `Class` class. It may need a field or two for static/construct methods
var aType = a.type
// using `Class.responds(signature:String, static:Bool)` (would be unable to tell construct)
aType.responds("getter", false)
aType.responds("setter=(_)", true)
aType.responds("new(_)", true) // This is the construct but it could act as a static?
// using more verbose "signature" parameter
aType.responds("getter")
aType.responds("static setter=(_)")
aType.responds("construct new()")
```

-----

Also, if possible, we should make this information query-able from the C API as well so foreign methods can also verify that values implement certain interfaces.

-----

_Oh, and I believe any of the `Fn` and `Fiber` values would claim to implement the `call(...)` methods since they kinda just expose all those methods for every possible arity. Even if the arity of the value doesn't match the arity of the signature._

Could get around this by checking if a value implements `arity`, then check if the arity is sufficient (though this won't work in foreign function calls when the VM is running.).

**Comment by CrazyInfin8** [comment]
> That said nothing forbids to try to call the function in a fiber, and
handle the error manually. Though, it would be more a band aid than
something I'll consider good practice...

I also think this isn't a good solution. If the method has side effects and you want to simply validate that the value has the method, your stuck with the dilemma of activating that side effect or not validating at all.

**Comment by mhermier** [comment]
Thinking at it, this seems to be a subset of my proposition about
interfaces. Since it is meant to allow to test if an object/class implement
an interface, one can test if an object/class implement an interface of a
single method (without the hurdle of managing method signature encoding)

**Comment by mhermier** [comment]
Side note: Don't trust immutability in wren. `YourClass.attributes` can be manually overloaded returning a fake object.
You can't fool the VM, but you can fool wren code. Trust me, I tried far worse faking `type` to augment the data it provides using some sort of *template compiler*...

**Comment by Jummit** [comment]
Just for clarity: was this actually completed? If not, I think it should be closed as not planned.

**Comment by clsource** [comment]
I just though that I feel satisfied with the answers. If anyone feels to continue this conversation may open a new issue and link this one 👍
