### ISSUE TITLE
Serialize (suspended) fibers or serialize the vm

### ISSUE THREAD

**Issue by dtornow** [wren-lang/wren#1174]
Hello. I have a question regarding fibers: Is there a possibility in wren to serialize and later deserialize a suspended fiber? Or alternatively, is there a possibility in wren to serialize and later deserialize a wren vm? 

The idea being that we could take a step in a computation, save the computation to disk, later read the computation from disk, take the next step of the computation ♾️

Thank you

**Comment by mhermier** [comment]
Usually this is not what you want to do. Most systems encourage to store
state instead of the inflight state. Some systems exist in the wild like
hybernation of process, or full environ serialization. In the case of wren,
it does not exist as this. While maybe it could be done to some extent,
there are quite some challenges to consider, like deserializing to a
different version... Mainly for that reason I would encourage saving state
instead of hybernation.

**Comment by dtornow** [comment]
Hey Michel, thanks for your response. Yes, valid point of view and a valid concern. There is increasing interest in serializable coroutines/serializable continuations to implement durable executions/workflows, so I was wondering if Wren could be a candidate for serialization/hibernation

**Comment by mhermier** [comment]
To complement on the subject fibers and coroutine are not exactly the same
thing. That said fibers can be suspended by "transfer" so technically, it
is only a question of restoring the stack, and it is a huge task unless
serialization is considered at low levels. As such there are quite a lot of
details to adjust for that, like byte code and foreign call serialization,
which are not really trivial.
All in all, for question on integrity of code/data, I think making a full
memory snapshot is the only practical solution (If we consider fiber
serialization to be available). Other solution might get to complex, and
would solve to little.

**Comment by dtornow** [comment]
Thanks for your detailed explanation, Michel 🚀
