### ISSUE TITLE
is Wren dead?

### ISSUE THREAD

**Issue by Triangle345** [wren-lang/wren#1180]
Looks like there have not been updates for quite some time? Are pull requests still being accepted? Is the language still being worked on?

**Comment by ruby0x1** [comment]
nope not dead, yes still being worked on. PRs are processed in bulk when handling them.

Wren is maintained by volunteers that are using it full time (including in a game engine + a commercial game shipping with it) so the changes come in waves. It's been a while since the last wave but.

It's worth reiterating that changes to a repo doesn't indicate anything, if a project is stable, reliable and working great for users it doesn't always need change for change sake. Wren is in a decent spot for it's primary use case, and will continue to evolve by real world use over time. 

Thanks!

**Comment by Triangle345** [comment]
Thanks for the reply! I support what you all are doing here so I was just curious.
