### ISSUE TITLE
Returning an object in Fiber.abort

### ISSUE THREAD

**Issue by gsmaverick** [wren-lang/wren#134]
Strings are good but it would be awesome to be able to give a `Fiber.abort` an object as an argument to allow more information to be passed back to the calling Fiber. As long as `toString` is implemented it seems like we would have at least everything we have now.

**Comment by munificent** [comment]
I've thought about that, but it does add some complexity. When a runtime error occurs, the VM needs to be able to print it directly and immediately. If the error is always a string, it can just print it as a C string. If we allow arbitrary objects, that means in the middle of a runtime error, it may be have to spin up a *new* fiber to execute the error object's `toString` method (which may itself fail!).

I suppose the other option is to call `toString` on the error object in `Fiber.abort` and have the VM store both the original error object and the resulting error message string, but that still feels a little more complex than necessary.

But, you may be right that we should have something more general here. I don't want to do it yet because I'd like to see how far we can get with something more minimal, but I'll leave this open.

**Comment by Qard** [comment]
Why not have an Error class that can be subclassed if one wants to pass extra stuff along? The base class would require a message that could be fetched out even on the native side, without having to spin up a new fiber to specifically call `toString` on the object.

**Comment by munificent** [comment]
That's not a bad idea, though there are still a few challenges. Many runtime errors come from within the VM. And, for those, it's nice that we can just create a bare string and store it in the fiber. Creating an Error object with a field whose value is a string is a little more work. As always, a key guiding principle is to keep the VM as simple as possible (but no simpler).
