### ISSUE TITLE
Relative import?

### ISSUE THREAD

**Issue by Qard** [wren-lang/wren#325]
I'm trying to figure out a way to do a node.js-style relative import, but `loadModuleFn` doesn't seem to be quite enough on its own. I can adjust the base directory before the import, but can't figure out how to restore it again after the module fiber runs. I need something to hook into there for sequential import statements to be rooted at the correct level. Any ideas?

**Comment by munificent** [comment]
> I'm trying to figure out a way to do a node.js-style relative import, but loadModuleFn doesn't seem to be quite enough on its own.

Right, it's context free. You know the import string, but not where it appears.

This is sort of by design, though it may not ultimately be the right design. I like the idea of an import saying *what* you want to import more so than *where you want to go from the current module to find it*. Being context-free in that way makes it easier to rearrange files, support package managers, etc.

It's, more or less, how Java, C#, and C/C++ tend to work, if you wave your hands around include paths, classpaths, .cvproj files, etc.

But it can also be tedious and verbose in the presence of a lot of nesting, and it's not clear how the CLI should locate the "root" that absolute imports are imported relative from. (Right now, it's the directory where the main script appears, but that's not ideal.)

The import system in Wren is really rudimentary right now. I wanted to get enough in place to start experimenting. And, more important to me at the time, start playing with the actual runtime semantics of modules and scope. But it definitely needs a lot of work and probably a lot of experimentation.

One option to try might be to have a syntax that means "relative import". Perhaps a leading dot in the import string. Then, when the VM sees that, it prepends the containing module's path. Though, once we do that, we'll want to be able to back out of directories too. We'll likely end up with something like [Python's syntax for relative imports](https://docs.python.org/2.5/whatsnew/pep-328.html).

I'm not sure if that's a good thing or a bad thing. What do you think?

**Comment by Qard** [comment]
Yeah, I had actually been thinking ./ for relative and bare to search a wren_modules folder, like node. The relative search doesn't currently work though. :(
