### ISSUE TITLE
Scheduler does not drain?

### ISSUE THREAD

**Issue by Qard** [wren-lang/wren#326]
Is it expected behaviour that tasks added to the Scheduler don't drain after execution?

Given some code like this:

```
import "scheduler" for Scheduler
import "io" for File

Scheduler.add {
  System.print("before")
}

System.print(File.read("test.wren"))

Scheduler.add {
  System.print("after")
}
```

The before will print, then the File.read(...) will print, but the after will never print. Is it possible to drain the scheduler automatically before the root fiber ends?

**Comment by munificent** [comment]
It's, uh, neither expected nor not expected. :)

The scheduling stuff is still quite new and I'm still getting a feel for how to integrate libuv into a language with fibers. My hunch is that it probably should drain by default but I wouldn't be surprised if that also turns out to be the wrong guess. We might not know for certain until we have more of libuv supported and more interesting concurrent programs written in Wren.

I'm definitely leaving this bug open, though, because we should have some deliberate strategy here. :)

> Is it possible to drain the scheduler automatically before the root fiber ends?

Automatically, no. Not yet, at least.

**Comment by Qard** [comment]
I'm kind of suspecting the scheduler should actually be part of the core rather than the module collection, and have it drain when execution ends, much like the event loop and task queues in node.

The scheduler is the only component in module that I see which is really tied into everything. If it was in core, the stuff in module could more easily be accomplished as userland modules. I'm also debating if libuv should also be considered part of the core. I'm less convinced of that though.

**Comment by munificent** [comment]
> The scheduler is the only component in module that I see which is really tied into everything.

It's tied to all of the other CLI modules that do IO, but it's not tied to anything in core or the optional modules random and meta.

> I'm also debating if libuv should also be considered part of the core. I'm less convinced of that though.

It shouldn't be. Wren has a CLI which uses libuv, but the language itself is equally intended to be used as an embedded scripting language that runs on a lot of platforms and has no dependencies. Requiring libuv in core would definitely break that.

Think of it like this: node requires libuv, but V8 does not. Wren + core = V8. Wren + core + modules = node.

**Comment by Qard** [comment]
I was just thinking, this would be a good use for fiber finalizers. The scheduler module could internally do something like:

```
Fiber.current.addFinalizer {
  Scheduler.runNextScheduled_()
}
```

That would cause the scheduler to drain before the fiber completes.
