### ISSUE TITLE
Fiber finalizers and transition events

### ISSUE THREAD

**Issue by Qard** [wren-lang/wren#340]
I've been noticing a few cases where fiber finalizers would be really helpful. (#326, #294)

I propose a method on the Fiber class to add finalizers to a fiber which will run immediately before it completes, successfully or otherwise. This would allow a safe try/finally, by running a finalizer to clean up resources like file handles before unwinding the stack.

I also propose a static method to watch for fiber transition events and run a supplied block before it occurs, which receives a reference to the fiber that is to be transitioned to. This would allow for automatically applying finalizers to newly entered fibers which could be used to drain the scheduler at the completion time of any fiber.

**Comment by munificent** [comment]
I think we would want to drain only at the point that we complete the *last* fiber. By "last", I mean a fiber that doesn't have any other fiber to return to. We don't want to bounce to the scheduler during arbitrary fiber transitions. Fibers are not *only* for IO, and it would be a real problem if the user can't predict which fiber calls will interleave IO and which won't.

> I propose a method on the Fiber class to add finalizers to a fiber which will run immediately before it completes, successfully or otherwise. 

`.try(_)` effectively is that, but I think you have something else in mind. Can you show me some examples of how you'd use it?

> I also propose a static method to watch for fiber transition events and run a supplied block before it occurs, which receives a reference to the fiber that is to be transitioned to.

I could be wrong, but I don't think we need this. (And, if possible, I'd like to avoid adding it, to keep `Fiber` as minimal as possible.) I believe this is something only the CLI's scheduler needs and since it controls its own fiber transitions anyway, it could probably put this logic in there.
