### ISSUE TITLE
Keyword arguments?

### ISSUE THREAD

**Issue by refi64** [wren-lang/wren#341]
Sorry; I know this probably isn't the place for questions, but I couldn't find anything else, so this is what I'm going with...

Does Wren have a syntax like Python's keyword arguments? From what I've seen, this isn't possible except by passing a dictionary (e.g. `f.call({"a": 1, "b": 2})`), which isn't very concise. I'm looking for something like:

``` python
def f(...): ...

f(
    something=1,
    something_else=2,
    stuff=3,
    more_stuff=4,
    # etc.
)
```

Thanks in advance!

**Comment by munificent** [comment]
> I couldn't find anything else, so this is what I'm going with...

The [mailing list](https://groups.google.com/forum/#!forum/wren-lang) is the canonical answer for this, but here is OK too. :)

> Does Wren have a syntax like Python's keyword arguments?

Not currently, no. For things like *optional* arguments, where you have a lot of different combinations of arguments that are all valid, then passing a map is a good solution, I think. There's a little bit of punctuation, but I don't think it's too bad. For what it's worth, that's the way to do it in JS too. (Though Wren is a little more verbose because it requires quoting the keys.)

For cases where you have a few different specific sets of arguments and you want them to be named to make the callsite easier to read, I have been pondering adding them to the language. I am thinking of them a similar to keyword selectors in Smalltalk (and by extension Objective-C) where the keywords form part of the method signature itself. It would let you do stuff like:

```
Point.new(x: 1, y: 2)
Point.new(theta: 0.234, radius: 5)

random.int(min: 1, max: 5)
random.int(max: 5)
```

Note that each of these would be totally different *methods*, with signatures `new(x:,y:)`, `new(theta:,radius:)`, `int(min:,max:)`, and `int(max:)`, respectively. This is really useful because it lets you implement them separately and speeds up dispatching to the right logic.

But it makes them a poor fit for a long list of optional parameters. To support every combination, you would need a separate method for each combination.

**Comment by hauptmech** [comment]
Python gets this right with *args and **kwds absorbing all extra arguments into an array and map.

**Comment by munificent** [comment]
> Python gets this right with args and *kwds absorbing all extra arguments into an array and map.

Like many features, it's a trade-off.

Python's behavior does some things really well:

* It's conceptually simple. Users already know how to work with lists and dicts, so it takes advantage of that by building on top of them.

* It's very flexible for handling optional parameters.

* It gives callers the freedom to choose whether to pass parameters by name or not.

But it has some downsides:

* It's slower. A list and/or dict has to be allocated and the parameters added to it. That can require a lot of allocation and work.

* It doesn't let an API define *required* but *named* parameters. Naming implies optionality.

* It's much harder to statically analyze. Wren isn't statically-typed, but it was designed to be somewhat more declarative and amenable to static analysis than most other dynamic languages. Using imperative code to handle named parameters makes that nigh impossible.

Those downsides are all important to me, so I don't feel that Python's approach is a good fit for Wren.

**Comment by hauptmech** [comment]
I'm not sure what your assumptions are on the implementation side, and I'm guessing about when you are[ talking about the caller vs callee side](https://en.wikipedia.org/wiki/Parameter_%28computer_programming%29#Parameters_and_arguments) , so keep that in mind with the following...

> It's slower. A list and/or dict has to be allocated and the parameters added to it. That can require a lot of allocation and work.

But only when the coder adds the receivers `*positional` and `**named`. The coder can optimize later (the appropriate time for optimization) by refactoring the function to use exactly the parameters she found she needed in the end. 

> It doesn't let an API define required but named parameters. Naming implies optionality.

I'm not understanding you here. Each parameter (name) in a function definition is a required parameter.  The '=defaultvalue' part is what adds optionality. Exceptions are the `*` and `**` which are not parameters but denote the willingness to accept 0 or more of each respective kind of argument. They are type designators in a language that otherwise has no types.

On the call side we use named aguments for convenience, to let us specify them out of sequence, or (in python) create ad-hoc arguments.

Do you have any plans for any kind of vararg functionality?

**Comment by munificent** [comment]
> But only when the coder adds the receivers *positional and **named.

Yes, that's what I was referring to. I should have been clearer. I don't have a lot of Python experience, and I forgot that you can passed named parameters even without using `**kwargs`.

> On the call side we use named aguments for convenience, to let us specify them out of sequence, or (in python) create ad-hoc arguments.

Maybe I'm too much of a stickler for consistency, but I've never found being able to specify them in arbitrary order to be much of a selling point. I *do* really like the readability of named parameters. But my preference is more of the Smalltalk/Objective-C variety where the named parameters form part of the method name and have an explicit ordering.

That style of keyword arguments is a better fit for Wren in general because it lines up with Wren's concept of [signature and overloading by arity](http://wren.io/method-calls.html#signature). Named parameters would just become part of the signature and would thus be different methods.

**Comment by hauptmech** [comment]
So you're really looking at a adding a little syntactic sugar (which can be nice).

```
class A{
  construct new(){}
  aaarg(r,g){ "aaa"+"r"*r+"g"*g }
  aaack(c,k){ "aaa"+"c"*c+"k"*k }
}

class B {
  construct new(){}
  aaa(r,g){ "aaa"+"r"*r+"g"*g }
  aaa(c,k){ "aaa"+"c"*c+"k"*k }
}

var a = A.new()
var b = B.new()
```

`System.print( b.aaa(r: 2, g: 4) )` instead of `System.print( a.aaack(2,4) )`

How would one call a function with no keywords? (Or what would the definition syntax look like)?

**Comment by minirop** [comment]
@hauptmech, We lose variable names, so:
```
class B {
  construct new(){}
  aaa(r,g){ "aaa"+"r"*r+"g"*g }
  aaa(c,k){ "aaa"+"c"*c+"k"*k }
}

var b = B.new()
```
would still not compile (ambiguity), I suppose you would have to do:
```
class B {
  construct new(){}
  aaa(r:,g:){ "aaa"+"r"*r+"g"*g }
  aaa(c,k){ "aaa"+"c"*c+"k"*k }
}

var b = B.new()
System.print( b.aaa(r: 2, g: 4) ) // calls "aaa(r:,g:)"
System.print( b.aaa(2, 4) ) // calls "aaa(c,k)"
```

**Comment by munificent** [comment]
> So you're really looking at a adding a little syntactic sugar (which can be nice).

Considering it, yes. :) It's not the highest priority, but I've definitely encountered APIs where I felt names with the parameters would make it clearer. For example, consider a random number generator that let you pick numbers in a range:

```
random.range(3, 5)
```

Is that min and max? Min and count? Something like this might be nice:

```
random.range(min: 3, max: 5)
```

> How would one call a function with no keywords?

Just like you do today. Unlike languages like Python and C#, the approach we're talking about here would make named parameters explicit and distinct from positional ones. It's not that you can choose to pass an argument by name or not, it's that the API designer chooses which parameters are named and which are not.

> (Or what would the definition syntax look like)?

We'd need to distinguish named parameters from unnamed ones, so it could look something like:

```
class A {
  construct new() {}
  foo(a, b) { System.print("positional %(a) %(b)") }
  foo(first: a, second: b) { System.print("named %(a) %(b)") }
}

var a = A.new()
a.foo(1, 2) // positional 1 2
a.foo(first: 1, second: 2) // named 1 2
```

That's just one option, though. I haven't put any real time or effort into this. :)
