### ISSUE TITLE
Import Syntax

### ISSUE THREAD

**Issue by Web-eWorks** [wren-lang/wren#346]
Just something I thought I'd throw out there -- A slight change to the `import` syntax.

Currently you do `import "test" for test1, test2`.  While this is understandable, it seems a little unintuitive to me.

I think something along the lines of `import test1, test2 from "test"` or `from "test" import test1, test2`, if you want to go the python route, would perhaps be more intuitive. (Dropping the quotes would also be preferred.)

**Comment by munificent** [comment]
Ah, it's good that you brought this up. I would like to do some improvements here, though every attempt I've made so far hasn't panned out. At the very least, I should write down my thoughts on how it was designed and how it differs from Python.

In Python, you are always importing objects and binding them to variables. When you do:

```python
import thing
```

Python looks up a module (also named "thing"), and then creates a top level variable in your module bound to that module object.

When you do:

```python
from thing import stuff
```

Python looks up a module "thing", and then creates a top level variable "stuff" bound to "stuff" from that module.

So, in Python, the object of the verb "import" is always the *variable that gets created in your top level scope*. It also coincidentally refers to the name of the module you are importing in the `import foo` form, but that's a shorthand. The primary meaning of "import" is "what variables should I create".

Given that, a form like:

```
import thing for stuff
```

Wouldn't make sense in Python. You don't import modules, you import variables. "thing" isn't being imported, "stuff" is.

The challenge Python faced, then is how to arrange the syntax when you want to import a list of variables from a module. If you have some syntactic form that takes an open-ended list, you usually want that to be at the tail end. Otherwise, it's too easy for the reader to miss any important bits *after* the list. Imagine if Python had chosen this syntax instead of `from`:

```python
import stuff from thing
```

You'll notice that actually reads a little more naturally than the syntax they *did* choose. In common speech, we rarely put a "from" clause first. The problem is that this syntax doesn't scale well:

```python
import stuff, more_stuff, lot_of_stuff, so_much_stuff, yeah_lots from thing
```

It's hard to find the important `from thing` bit at the end. So they rearranged the clauses even though they read a little weirder that way, and even though it means every import line doesn't start with the same keyword.

---

Wren is different. In Wren, the object of "import" is the module itself. In Wren, you can do:

```
import "foo"
```

This imports a module, but it binds no variables at all, so "import" isn't about variables, it's about loading code. You can *also* bind variables (and in practice you almost always do), but that's secondary.

That lets us avoid the flipped syntax Python needs to do. We can have syntax that always starts with the module to import, and is then followed by the optional list of variables to bind. The remaining question is what keyword to use. Conveniently, I think `for` has about the right meaning and is already a reserved word, so I picked that:

```
import "thing"
import "thing" for stuff
```

The nice thing is that it means a series of import lines always start the same way, even if some bind variables and some don't. At the same time, the variable list is at the end, which is good in case it gets long:

```
import "thing"
import "thing" for stuff, more_stuff, lot_of_stuff, so_much_stuff, yeah_lots
```

There are still some improvements we could make. The syntax feels annoyingly redundant in the common case where a module exposes a single class:

```
import "scheduler" for Scheduler
```

And I wouldn't mind an unquoted form either. The nice thing about quoting it is that it gives an opaque string we can hand directly to the host application, so it decouples the VM itself from details of module resolution.

Still, import syntax (and semantics) is on my list of things to revisit once we have more third-party code, and more code reuse in general. At the time I designed the syntax, there literally were no Wren programs that were broken into multiple files, so it was hard to get a sense for how the syntax worked out in practice.

This was the best I could come up with at the time, but I wouldn't be surprised if we could improve it. I'll leave this bug open so we can track that, though my personal feeling is that adopting Python's syntax in particular wouldn't be an improvement.

**Comment by underscorediscovery** [comment]
To me the unquoted version is just a parser difference, what it finds, and how it treats what it finds can still be treated as a plain string just as it is now. 

This gets a bit weird is when the import would contain anything more than a simple singular name like the common example. Originally I had thought that the quotes were redundant but after playing with more importing styles (like `import "some/file/from/folder"` or like dart `import "some:thing/here.dart"`) it may reduce clarity when these get longer:

```js
import some:thing/from/some/other.dart for Something
import https://gist.github.com/something/else.wren for Else
import "some:thing/from/some/other.dart" for Something
import "https://gist.github.com/something/else.wren" for Else
```

It might not complicate the parsing (since the end marker is always for or new line) but the quotes definitely separate where the module name starts and ends for reading. This could also be handled by the syntax highlighting, but I use js syntax above to make a point: it also has to deal with keywords being inside of the import string and it gets hairy pretty quickly.

I'm of the opinion at the moment that the quotes are a bit clearer, and simpler.

**Comment by munificent** [comment]
> I use js syntax above to make a point: it also has to deal with keywords being inside of the import string and it could get tricky pretty quickly.

Yes, there are a couple of other cases where a user might be surprised how the tokenizer handles what they informally think of an import "string:

```
import pointless/double//slash/is/valid/path for Something
// Oops! That's a line comment!

import ../from/parent/directory
// Oops! That's a range operator.

The latter we could handle by special casing it. The former is a lot trickier. :) If we were to allow unquoted imports, I think we'd want to limit them to a series of dotted identifiers as in Java, C#, Python.

**Comment by underscorediscovery** [comment]
Right yea! 

I do like the flexibility of making the import use case specific on the vm side, i.e just the plain string. This can be interpreted however desired... so I haven't thought about there being a dotted or "uniform import syntax". Those usually follow some form of rules relating to folders, which makes sense if you have a class path construct to look up modules, but in the current vm model it's designed to allow the user to load the modules from wherever it needs to, right? I'd be curious if there's an overlap of consistent import specifier and flexibility to reinterpret that .

**Comment by munificent** [comment]
> it's designed to allow the user to load the modules from wherever it needs to, right?

Exactly right.

**Comment by munificent** [comment]
> I would suggest that the plain import 'x' syntax, if the module x provides a top level variable 'X', would import that implicitly. 

That feels a little magical to me. We'd also have to handle cases like:

```
import "foo_bar"
```

Providing a top level variable named FooBar. Having the rules to translate between underscore_separated and CamelCase encoded into the language and VM feels pretty sketchy to me. What happens when you do:

```
import "ftp_stuff"
```

And expect that to create a variable named `FTPStuff`, not `FtpStuff`?

Don't get me wrong. I don't like the redundancy either, but I think the right direction—if we do anything—is to probably infer the import path from the imported identifier, and not vice versa.

This is something I think will probably need some changes.

> One thing I would request - file relative imports.

Oh, yes! I feel your pain. I know the current behavior doesn't really work at all.

This is something I have some experience with, since I wrote the package manager for Dart and dealt with all of the underlying machinery around how references to other files are resolved. It's not simple.

What we have in Wren today is clearly not sufficient, but getting to a good solution will take some work and I haven't carved out the time yet. Relative imports are part of that.

**Comment by bjorn** [comment]
> That feels a little magical to me.

That's a misunderstanding. He was suggesting that importing any module without specifying any "for", will import _all_ that modules top-level variables in the current scope.

I think it's a nice suggestion, and it would be especially useful when a lot of classes are exposed by a module. However, I think there are problems with name collisions. Also, there would be no way left to import a module without binding any variables. I would personally propose this to work more like:

```qml
import "foo_bar" as fb
```

Now, there would be a local variable `fb` through which you could access any top-level variables in the "foo_bar" module.

**Comment by munificent** [comment]
> He was suggesting that importing any module without specifying any "for", will import all that modules top-level variables in the current scope.

Ah, OK.

That would be nice, but I've deliberately avoided that, for probably non-obvious reasons. By design, if you look at a single Wren source file, you can tell where every variable is declared. You don't need to actually know the contents of any other file that you're referencing. For static analyis, and general readability, I think that's a nice property to maintain, though it does make imports a bit more verbose.

>  I would personally propose this to work more like:
>
>     import "foo_bar" as fb
>
> Now, there would be a local variable fb through which you could access any top-level variables in the "foo_bar" module.

Yes! This would preserve the above property because then the "names" you import become *dynamically dispatched* members on the lexically scoped `fb`.

Alas, I have yet to come up with an implementation for this that I like. Several months ago, I spent a *ton* of time trying out a lot of different experimental ways to make modules work more like first-class objects. I failed to get anything that hung together well. Every approach I tried had some nice properties but some other really bad ones, and I eventually gave up. For now at least. :(

**Comment by 0x00A** [comment]
A `commonjs` style import wouldn't require any grammar. It's pretty great in terms of how everything that gets imported is explicitly named by the importer (no variable clobbering and no need to disambiguate with namespaces, etc). I think a lot of developers would find it pretty easy to reason about since its been in nodejs/front end tooling for so long now (also the behavior is [`well defined`](https://nodejs.org/api/modules.html#modules_all_together))... It seems like a pretty natural fit...

```js
var x = require('./foo') // a local module
var x = require('foo') // a core module or an installed module
```

**Comment by 0x00A** [comment]
PR #327 is awesome!

> Personally, I like the current model of npm, supporting nested dependencies, but trying to flatten as much as possible.

**Comment by Qard** [comment]
It might be good for the syntax to require strings, like `import "foo" as foo`, so the VM users can define their own module resolution algorithm, or extend the default one. For example, one might want to support `import "res://foo" as foo` and `import "doc://bar" as bar` to load code from an applications resources or its documents directory on iOS. Another possibility is adding loading code over the network like `import "http://example.com/code"`.

**Comment by underscorediscovery** [comment]
That's already how it works yea :) You implement the load callback and it handles you the string that was imported and can do whatever, which is great.

**Comment by Qard** [comment]
I meant specifically to allow that capability *in addition* to a more structured module resolution system, with support for overriding or extending in some way. So one could have something like:

```
// Attempt to find module with custom resolver (maybe using "res://foo" style)
module = customResolver(key)

// If customResolver returned null it'll flow into the default resolver
if (!module) {
  // "foo" maps to "wren_modules/foo" or something like that.
  module = defaultResolver(key)
}
```

I still want a more capable default resolution algorithm.

**Comment by underscorediscovery** [comment]
In the CLI, it makes a lot of sense to have some well defined resolution - as discussed above. 

Not that you're suggesting it be in the vm level - but rather to be more exact in my appreciation of how it works right now - I'll add some notes from some practical use on the vm level. 

I don't see _any_ benefit of an additional (potentially conflicting/confusing for end users) model in the vm. The vm obviously does not know _anything_ about os filesystems it may be running on (packed binary files, game consoles, networked or imaged data, android apk = zip file, etc), and must not. Therefore in every one of those situations, it's of little use. Then there's the issue of user facing scripting (modding), where sandboxing is almost 100% going to be done as step one, so I'd have to explicitly ignore this code path there as well. 

When viewed as a 99.9% use case of custom resolution and the tiny percent in the other code path, lugging around a potentially complex import system and IO systems to support it just seems unhelpful from an vm embedding perspective. 

Though it's worth mentioning the idea of an optional (but not internal) vm module (like random) that implements this type of resolution and acts as an adapter lets you have it both ways. `myloader -> vm` becomes `myloader -> customloader -> vm`. The custom loader accepts a load function and vm, and behaves like a drop in module that does what you're after.

All aside, the CLI part having some resolution process might be useful.
