### ISSUE TITLE
Switch or match statement

### ISSUE THREAD

**Issue by dgreensp** [wren-lang/wren#352]
JavaScript has a C-style `switch`.  Some languages have a cleaner, more modern syntax for much the same thing, and then of course there are languages with actual pattern-matching.  Wren doesn't have any of these, right?  That's a bummer!

**Comment by munificent** [comment]
Pattern matching is [pretty close to my heart](http://magpie-lang.org/pattern-matching.html) and I've considered something like it for Wren. It's challenging to both do it well and yet keep it minimal, which is why we don't have anything like it yet.

We may be able to get by without it (Lua and Python do), but let's keep this open for now to see if we come up with anything.

**Comment by sbrl** [comment]
Related: #120

**Comment by Qard** [comment]
Agreed on holding off for a good implementation. I don't think the basic switch statement really adds much value beyond what if/else can already do. I'd like to see proper pattern-matching eventually.

**Comment by minirop** [comment]
What pattern-matching should be possible/are needed/wanted?

* on values (like a switch)
* on types (enhanced switch)
* destructuring

----

I just hacked a little type matching that looks like this:
```dart
var x = 3
match (x) {
    List | Range => System.print("x is a list or a range\n"),
    Num => System.print("x is a number\n"),
    else => System.print("x is of an unknown type\n")
}
```

I may try to do other things like:
```dart
var x = [1, 2, 3]
match (x) {
    [a, b] => System.print(a + b),
    [a, b, c] => System.print(a + b + c), // this would match
    else => System.print(x.count)
}
```

(and if I manage to detect the existence of getters)
```dart
class Wren {
    construct new() {}
    x { 3 }
    y { 5 }
}
var x = Wren.new()
match (x) {
    {x, y, z} => System.print(x + y + z), // no match 'cause no "z" getter.
    {x, y} => System.print(x + y), // this would match
    else => System.print("nada")
}
```

**Comment by munificent** [comment]
Yeah, when I think pattern matching, I definitely do tend to think of that whole bullet list. I mean, if you're gonna do it, why not do it right? ;)

At the same time, Wren *is* really minimal and I'm a little worried pattern matching could end up metastasizing on us: value matching, type matching, list destructing, map destructuring, object destructuring, etc. Ranges? Predicate clauses? Wildcards?

There's also the question of if we have pattern matching, do we do it right and deeply integrate into the language such that parameter lists and variable declaration statements use the same syntax and semantics. (The correct answer to this is: "Yes, if we are going to do it, we *should* do it right and use patterns for all name binding.") But *that* could mean possibly revisiting more of the language than we really want to.

It's definitely a feature I care a lot about, though, and if it turns out to not be a lot of complexity, I could see it happening.
