### ISSUE TITLE
Manual install

### ISSUE THREAD

**Issue by bfontaine** [wren-lang/wren#374]
Hello,
I’d like to manually install `wren` for a [Homebrew](http://brew.sh/) package, but I can’t find a way to do so without hacking around in the Makefile:
- Let it know where is `libuv` (or let it find it by itself) and disable that external download (installing `wren` should work offline)
- Specify an install prefix: it should then install things under e.g. `$PREFIX/bin`, `$PREFIX/lib`, etc.

The last bit is commonly done by passing a variable to the Makefile (e.g. `make install PREFIX=/usr/local`).

Thanks!

---

Update: this is what I ended up with: https://github.com/bfontaine/homebrew-languages/blob/636ff2795169bcf9d1a8ed57455b103a83452bd3/Formula/wren.rb#L18-L30

It’s equivalent to something like:

``` sh
# Trick it into thinking gyp is already installed
mkdir -p deps/libuv/build/gyp/gyp

# Use -o not to check the age of these files when building
make -f util/wren.mk -o deps/libuv/build/gyp/gyp -o /your/path/to/libuv.a LIBUV=/your/path/to/libuv.a

mv bin $PREFIX/
mv lib $PREFIX/
```

**Comment by paulsapps** [comment]
I wonder if adding libuv as a submodule is a good idea? That would also fix the appveyor build too.

**Comment by munificent** [comment]
> The last bit is commonly done by passing a variable to the Makefile (e.g. make install PREFIX=/usr/local).

I'm definitely up for adding this if it's helpful. I'm kind of a make noob, so I didn't the simplest thing that worked when I created it.

> I wonder if adding libuv as a submodule is a good idea?

Yeah, maybe. I didn't set it up that way initially because submodules are a bit of a pain to use. In particular, it means a simple git clone doesn't actually give you everything you need. You need to remember to get the submodules too.

Now that `git clone` and `git pull` support `--recurse-submodules`, maybe we should switch to use them?
