### ISSUE TITLE
Explicit length for `wrenInterpret`

### ISSUE THREAD

**Issue by ayosec** [wren-lang/wren#407]
Currently, `wrenInterpret` expects that the source is terminated with a null character (i.e. a regular C string). It would be useful to have an alternative way to execute Wren code without the `\0` terminator.

Something like:

```c
WrenInterpretResult wrenInterpretBytes(WrenVM* vm, const char* source, size_t length);
```

**Comment by munificent** [comment]
Yeah, that's doable, though it means tweaking a few things in the compiler. Is having to terminate the source string with a `\0` a pain?

In the FFI, it's useful to be able to pass in an explicit byte array with a given length because:

1. Wren supports strings containing NUL bytes inside them. You can use a string as an arbitrary byte buffer.

2. If you don't give an explicit length, it needs to call `strlen()` to find it, which is O(n).

Neither of those apply to `wrenInterpret()`. Source files can't contain internal NUL bytes. (We *could* allow them in comments, but I don't think it's that useful to.) The compiler already has to walk the characters in the string to compile the code, so there's no performance benefit of an explicit length.

We could still support an explicit length API like you suggest, I just want to make sure it's worth the additional code in Wren.

**Comment by ayosec** [comment]
> Is having to terminate the source string with a `\0` a pain?

The problem is when someone tries to use Wren in a language where strings are defined using an explicit length, instead of being null-terminated. In my case, I have the issue in Rust.

Anyway, it is not a critical issue. A simple work-around is to duplicate the data, and then append the `\0` character. Rust has support for this in its std, via [`CString`](https://doc.rust-lang.org/std/ffi/struct.CString.html), so the fix is simple (with some overhead, though).

If the change requires too much internal changes, please, feel free to discard this issue.
