### ISSUE TITLE
WrenHandle receiver get nulled after double import

### ISSUE THREAD

**Issue by fabricemarie** [wren-lang/wren#410]
In a module called foo, I define a class that has a static method called `processEvent(event)`.
In the main module, after importing the foo module, I get a valid receiver and method handles:
```
wrenGetVariable(vm, mod, toStringz(className), 0);
WrenHandle* receiver = wrenGetSlotHandle(vm, 0);
WrenHandle* method = wrenMakeCallHandle(vm, "processEvent(_)");
```
I can call successfully the method fine with `wrenCall()` multiple times, until I call  `import foo` again. At that stage my receiver somehow gets nulled, and wren returns the following error message:
```
Null does not implement 'processEvent(_)'
```

Did I do something wrong, or is this a real issue?
From reading the documentation and looking at the VM code, it looks like the double import is supposed to do nothing, so it should not have such side-effect.

**Comment by fabricemarie** [comment]
Actually, after more tests, the receiver handle get nulled after running wrenInterpret again.

Step to reproduce:
```
wrenInterpret(vm, "import \"mymodule\"\n");
...get the receiver handle and method handle...
wrenInterpret(vm, "...");
... receiver handle now points to a wren null value...
```

**Comment by iangodin** [comment]
I had the exact same bug, with similar circumstance.

This started happening to me with commit a3aaad83eaa816f774de036be5d29dbeb617d1fe.
This commit saves and restores the vm->apiStack in functions callForeign and createForeign.
(see issue #362 and #394).
I think this is correct, but it appears to have revealed a bug.

The call to wrenInterpret switches fiber (which is where the stack is stored).
But then the vm->apiStack is then pointing to another fiber's stack.
So you set value for a slot on the apiStack, but then wrenCall is using the fiber's stack.

I think the fix is to NULL the apiStack when the fiber changes.
Add the following at the top of the runInterpreter function (in wren_vm.c, around line 696):
if ( vm->fiber != fiber )
        vm->apiStack = NULL;

At least this worked for me, but I am still studying it (first time diving deep in the wren internals).

**Comment by munificent** [comment]
I believe this is fixed by https://github.com/wren-lang/wren/pull/655, which removes the local caching of `apiStack`. I'm going to speculatively close this assuming that's true but if happen to repro this, let me know and I'll reopen.
