### ISSUE TITLE
Support enum and immutable variables

### ISSUE THREAD

**Issue by SuperWangKai** [wren-lang/wren#423]
Maybe we should treat ALL_CAPS variable as immutable?

**Comment by munificent** [comment]
Yeah, I've been considering the same thing. :)

Instead of ALL_CAPS, it might make more sense and be more consistent to apply it to any identifier that starts with a capital letter. That matches the scoping rules and means things like class declarations would be constant (as they generally should be).

**Comment by SuperWangKai** [comment]
That's wonderful! What about enumeration? It seems that enum is very friendly / necessary to game development.

**Comment by macabeus** [comment]
Yeah, I think that `enum` is very useful to Wren. But how will be it?

I really like the [Swift's enum](https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html), but it is too complex to Wren. Maybe we should do a simplify version to Wren, something like:

```
enum Directions {
    case north
    case south
    case east
    case west
}

class Man {
  static walk(direction) {
    switch direction on Directions {
      case .north:
        ...
      case .south:
        ...
      case .north:
        ...
      case .east:
        ...
    }
  }

  static walk2(direction) {
    switch direction on Directions {
      case .north:
        ...
      case .south:
        ...
      otherwise:
        ...
    }
  }
}

var direction = CompassPoint.north
Man.walk(direction)
```

A switch should be have **all** cases of the enum, **or** the **otherwise** keyword.

**Comment by SuperWangKai** [comment]
It's nature to have `enum` or `immutable ` for Wren since we need to handle `enum` or `const` in C/C++.

**Comment by macabeus** [comment]
@underscorediscovery What is the reasoning to close this issue?

**Comment by underscorediscovery** [comment]
Just cleaning up the issue list at the moment. 
It was meant to have the future tag applied, so we can revisit. I added it now!
