### ISSUE TITLE
Parameter syntax

### ISSUE THREAD

**Issue by ghost** [wren-lang/wren#449]
The |a,b| syntax for function parameters is unbearable (love everything else). I want to embed Wren in a user-facing process engine, but this will be too hard to explain (they know enough javascript to be dangerous)

Any chance Wren can gain support for the *expected* fun(a, b) syntax? If I fork Wren, would it be hard to change this, or is the |a,b| syntax deeply integrated into the language?

Thanks.

**Comment by minirop** [comment]
there are no "fun" keyword to say "here's a function". in fact, there are no functions at all in Wren. This syntax is the only one possible to simulate a pointer-to-function (aka callback).

**Comment by bjorn** [comment]
If this is about:
```js
blondie.callMe {|first, last| 
  System.print("Hi, " + first + " " + last + "!") 
}
```
vs.
```javascript
blondie.callMe(function(first, last) {
  System.print("Hi, " + first + " " + last + "!") 
})
```
note how in Wren you don't need `(...)` around the call and this is one of the things making the code nicer to read in general. And sometimes you do use them to pass other parameters to the function, but they remain cleanly separated from the function you're passing in.

It would be redundant for Wren to support both syntaxis, and I think the latter would make Wren lose much of its style. Why not just embed JavaScript instead then? If it's about the size, you may want to look at [Duktape](http://duktape.org/index.html) instead.

**Comment by mhermier** [comment]
What about allowing the lambda notation? So it would look like:

```javascript
blondie.callMe \(first, last) {
  System.print("Hi, " + first + " " + last + "!")
}
```

There are pro and cons about that extra syntaxic sugar, but I found it elegant in its own way.

**Comment by munificent** [comment]
This corner of the grammar comes up a lot, so I should probably write some more detailed docs around it. Unfortunately, we can't support the normal syntax for parameters while also supporting block arguments because it's ambiguous. Consider:

```
foo.bar (a) { b }
```

Does this mean:

1. Call `foo.bar()`, passing in the value of `a` and a function of zero parameters.
2. Call `foo.bar()`, passing in a function that takes one parameter, `a`.

Block arguments are one of my favorite features of Wren's syntax, so I would hate to give those up. So that leads us to need some way to distinguish a parameter list before a block argument from an argument list. The syntax I chose is from Smalltalk by way of Ruby (which is where Wren also gets block arguments), so it's not a totally novel invention, though I admit it's a little weird at first.

@mhermier's suggestion of using `\` would work too. You just need *some* kind of marker to make the parameter list explicit. I don't think I like how that looks, though. One nice thing about Ruby's syntax — even though it's unfamiliar to many — is that it puts the parameter list *inside* the block. I like that that helps make the function a single visual unit. The entire function is contained with the `{` and `}`.

**Comment by mhermier** [comment]
I think all this comes with a miss-understanding of the language. Since users are mostly formatted with mostly "style free" language, the fact the position of the opening bracket is important, must make a path in their brain.

While I really like that solution, I really think the `\` is the way to go or at least it should make its way in the language.
Current implementation introduce an oddity in the language to specify the parameters.
The \ has the advantage to not introduce a keyword, but also can allow the possibility to override every form of invocation in wren language. Therefore, one could write:

1. `\{ a }`
2. `\=(a){ b }`
3. `\(a,b, ...) { z }`
4. `\(a,b, ...)=(y) { z }`

And since it follows the normal method definition signature it should be cheap to implement, and also benefits from all the change to the code path to the method definition.

That would also close a question about the possibility to shorten the "shorten" the function invocation syntax. If we want to support every variants of methods invocations then there is an issue with the getter form (1), since it would require to be able to write `foo.` and expect a value evaluation of it. While not impossible, supporting unary left `.` operator would be a huge burden and adds extra complexity.

And this brings us to renaming the `call` function to `value`. While I don't have anything against `call`, I think `value` will make more sense with the adoption of `\`. If we can also express the getter/setter syntax now form (2) `foo.call=42` invocation sounds odds, while `foo.value=42` less.
And has such Object could also have the method 'value { this }' which could make things even more fun and make the syntax even more looking like lambda language:
`
class Array {
 ......
  fill(value) {
    for (i in 0..count) this[i] = value.value
  }
}

var array = Array.new(42)
array.fill 42
var i = 0
array.fill \{ i = i + 1 }
`
I don't know if last part is realistic or if there are huge cons or implication in the language though.
