### ISSUE TITLE
define a wrenStringToNum() for foreign methods?

### ISSUE THREAD

**Issue by iweindesmedt** [wren-lang/wren#454]
Maybe it's a good idea to put the logic from `DEF_PRIMITIVE(num_fromString)` into a new `wren...` function, so this functionality is available (like `wrenNumToString`) to foreign methods

**Comment by mhermier** [comment]
Can you show a use case? I don't see a real one where it is not better to *force* the user to use Num::fromString() from wren language and deal with exceptions/errors from there.

**Comment by iweindesmedt** [comment]
A few reasons:
- There is `wrenNumToString`, so it seems intuitive to have `wrenStringToNum` too.
- `Num::toString()` uses `wrenNumToString` anyway, so why not have `Num::fromString()` use `wrenStringToNum` (or to use the same naming, maybe `wrenNumFromString`, but thats another discussion)
- Converting strings to numbers is a very common use case. For example getting input from stdin as a number, parsing a serial number like 'ABC-123' and split it in a string and number, and so on...

This way, this functionality would be 'globally' available through a `wren...` function instead of having to use `strtod` or any other string-to-num function.

**Comment by mhermier** [comment]
While I agree with all these arguments, they only are profs of form and not presence.
There are quite a number of use-case of strtod in the code base, in particular in the compiler, that would tend to validate its existence.
In the other hand there is only one caller of wrenNumToString so maybe it should be inlined.

**Comment by munificent** [comment]
> I don't see a real one where it is not better to force the user to use Num::fromString() from wren language and deal with exceptions/errors from there.

I think I generally agree with @mhermier here. In most cases, it should be cleaner to do the conversion in the Wren side of the code. If it's a pain, though, I could see adding support for this to the API.

I should point out that `wrenNumToString()` is *not* currently part of the public API for Wren. If it was, it would be declared in "wren.h". Its name starts with "wren" because it's used by other source files in the VM. That means it needs to be exported and visible to the linker and I want to ensure it doesn't collide with other functions in the host application. The only functions in Wren that aren't prefixed are static functions that are local to a single compilation unit.
