### ISSUE TITLE
memory corruption when accessing dynamically created class with different parent

### ISSUE THREAD

**Issue by skybrian** [wren-lang/wren#466]
```
var make_greeter = Fn.new {|parent, message|
    class child is parent {
        construct new(m) {
            _message = m
        }
        greet() {
            System.print(_message)
        }
    }
    return child.new(message)
}

class Dog {
    wag() {
        if (_wags == null) {
            _wags = 0
        }
        _wags = _wags + 1
    }
}

var dog = make_greeter.call(Dog, "bark!")
dog.greet()

make_greeter.call(Object, "hello!")

dog.greet()
```

Output looks like this:
```
bark!
bark!
wren(6600,0x7fffe9ee43c0) malloc: *** error for object 0x7f85ebc0ff80: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by skybrian** [comment]
I believe this has something to do with how the `METHOD_STATIC` and `METHOD_INSTANCE` ops are implemented. In `bindMethod`, it modifies the passed-in method's bytecode in place. But the method is loaded from a constant, so this isn't safe. It seems like it should copy the bytecode before modifying it.

If that's the culprit, this bug will happen whenever a `class` statement gets executed multiple times, with two different superclasses that have a different number of instance variables.

(I came up with this example while reading the source code to find out how Wren implements fields.)

**Comment by minirop** [comment]
I just tried and I don't have the crash myself.

But I do have an assert in debug: `[src/vm/wren_vm.c:987] Assert failed in runInterpreter(): Out of bounds field.`

**Comment by munificent** [comment]
Ooh, ouch! Yes, I think you're right. To handle this correctly, we probably will need to copy the bytecode. :-/  I'll have to think about this some more.

**Comment by mhermier** [comment]
For me it sounds more like a language issue. In the first place, class should not be allowed to be instantiated from function for now, and accepting it is an error. If we want to allow that, we need to (re)think about class scope.
AFAIK class creation implies registration of the class to module (unless it changed in previous month), and therefore "child" is created and redefined to the module on each call to the function.
That said I like the idea of having lower cased class names that register localy, but we need to think a little bit more to the langages and vm implications.

**Comment by munificent** [comment]
>  In the first place, class should not be allowed to be instantiated from function for now, and accepting it is an error.

Yes, the easiest fix would be to syntactically restrict class definitions to only appear at the top level.

We could probably do that without losing *too* much useful functionality. I think it's pretty rare for users to define classes inside methods, and ever rarer for those classes to inherit from a different class on each invocation.

That being said, the language *does* support this in almost all other respects. Things like closures and scope should work OK with nested classes. It's really just the bytecode binding of the superclass that's broken.

For the short term, the easiest fix may be to just disallow classes anywhere but the top level and see it users actually complain about the limitation.

**Comment by mhermier** [comment]
Le 22/10/2017 à 19:25, Bob Nystrom a écrit :
>
>     In the first place, class should not be allowed to be instantiated
>     from function for now, and accepting it is an error.
>
> Yes, the easiest fix would be to syntactically restrict class 
> definitions to only appear at the top level.
>
> We could probably do that without losing /too/ much useful 
> functionality. I think it's pretty rare for users to define classes 
> inside methods, and ever rarer for those classes to inherit from a 
> different class on each invocation.
>
Well there is a real use case as shown here, and in general with 
metaprograming I think.
>
> That being said, the language /does/ support this in almost all other 
> respects. Things like closures and scope should work OK with nested 
> classes. It's really just the bytecode binding of the superclass 
> that's broken.
>
> For the short term, the easiest fix may be to just disallow classes 
> anywhere but the top level and see it users actually complain about 
> the limitation.
>
This smell like a short short short term solution, and I think the 
complains exists already since there start to be *real* usage of it.
That said, a mid term solution would be to allow anonymous class 
definitions (something like we can find in java) to mitigate the 
complains. It would look like:

class [is Superclass] {
   [methods]
}

So one could instantiate a fresh class on each *hit* of this 
construction. It should return the class instance so it can be stored or 
instantiated with something like:

foo = class { }
class { } new()

The only problem I see is that currently, class implementation impose 
class to name them. While from my point of view name is not a property 
of class (but only really important for debugging purposes), we can 
solve the issue by constructing a fake class name. I propose somthing 
like "anonymous@module:line_number" but what ever is good for me.

**Comment by skybrian** [comment]
Another possibility might be to do a runtime check and fail if the class name is already defined in the module. So, you could only define each class name once, but you could use if statements to do conditional compilation.

**Comment by mhermier** [comment]
Well as this it is not possible, and would require adding quite a lot of
complexity in the namespace systems. By that I mean, a namespace for the
classes should be added to module, with the lookup and shadowing problems
it will add.
And in extra, it doesn't solve metaprogramming and only make it a bloating
source in code by forcing duplication.

Le 24 oct. 2017 5:37 AM, "Brian Slesinsky" <notifications@github.com> a
écrit :

Another possibility might be to do a runtime check and fail if the class
name is already defined in the module. So, you could only define each class
name once, but you could use if statements to do conditional compilation.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/munificent/wren/issues/466#issuecomment-338863194>, or mute
the thread

**Comment by skybrian** [comment]
I don't see why it would be all that hard to make a class statement always set a module variable. In classDefinition(), it might just be a matter of calling wrenDeclareVariable() instead of declareVariable()?

There's relatively little you can do by executing a class statement twice anyway. Only the superclass and any upvalues that the class happens to reference can be changed, as far as I can tell. If you want to change anything else you'll have to copy the class statement.

**Comment by mhermier** [comment]
While I agree with you, There is an issue that we where trying to avoid.
You can't say that "class Foo {}" is equivalent to "Foo = class {}".
It was designed differently to avoid, circular parenting. So you can't
write "class Foo is Foo" without warning, and ending with something
different to what you expect.

But now I start to wonder if it is not premature optimisation. I mean, we
can raise an error at runtime instead of compile time, and simplify a bunch
of code.

I would like to hear Bob comments on this. That way it would make "class
Foo {}" equivalent to "Foo = class {}" (at exception of naming) and it
sounds better if we were to allow anonymous class.

**Comment by munificent** [comment]
> I don't see why it would be all that hard to make a class statement always set a module variable. In classDefinition(), it might just be a matter of calling wrenDeclareVariable() instead of declareVariable()?

That feels like a wart to me. It would behave different from how other variables are declared, and vaguely feels like dynamic scope. Doing a declaration inside a block shouldn't produce a new variable in some outer block.

> There's relatively little you can do by executing a class statement twice anyway. Only the superclass and any upvalues that the class happens to reference can be changed...

Yes, local classes aren't super useful, but they just naturally fall out of how the grammar is constructed. Wren is an imperative language scripting language, so any statements allowed at the top level are also allowed inside blocks. You can import inside a block too for that matter.

The ideal solution (from the language semantics point of view) would be to just copy the code when binding methods instead of mutating it in place. It is a little strange to be mutating stuff in the constant table.

I'm thrilled by the idea of duplicating all of the code for every class declaration just to support a really unusual edge case, either, though.

> It was designed differently to avoid, circular parenting.

Ooh, that's a good point! We actually *don't* prevent that now. I think you can do:

```wren
var getFoo = Fn.new { Foo }

class Foo is (getFoo.call()) { ... }
```

Bad things will probably happen if you do that. :)

I'm not sure how feasible it is to prevent that syntactically, so we'll probably need to do a runtime cycle check.

**Comment by mhermier** [comment]
Le 27 oct. 2017 1:47 AM, "Bob Nystrom" <notifications@github.com> a écrit :

I don't see why it would be all that hard to make a class statement always
set a module variable. In classDefinition(), it might just be a matter of
calling wrenDeclareVariable() instead of declareVariable()?

That feels like a wart to me. It would behave different from how other
variables are declared, and vaguely feels like dynamic scope. Doing a
declaration inside a block shouldn't produce a new variable in some outer
block.

There's relatively little you can do by executing a class statement twice
anyway. Only the superclass and any upvalues that the class happens to
reference can be changed...

Yes, local classes aren't super useful, but they just naturally fall out of
how the grammar is constructed. Wren is an imperative language scripting
language, so any statements allowed at the top level are also allowed
inside blocks. You can import inside a block too for that matter.

Local class are useful at least in 3 major ways:

- Avoiding to poluate global scope with functional class (like java Actions
class)
- Hiding implementation details, you return a class that is a subclass, but
you don't want the user to know (factory style)
- meta programming, where you need to create a *fresh* class on each
invocation.

So you can't really say it is not that usefull or unusual. It is mostly a
matter of programming style, to force a clean *global*/*module* namespace.

The ideal solution (from the language semantics point of view) would be to
just copy the code when binding methods instead of mutating it in place. It
is a little strange to be mutating stuff in the constant table.

I'm thrilled by the idea of duplicating all of the code for every class
declaration just to support a really unusual edge case, either, though.

It was designed differently to avoid, circular parenting.

Ooh, that's a good point! We actually *don't* prevent that now. I think you
can do:

var getFoo = Fn.new { Foo }

class Foo is (getFoo.call()) { ... }

Bad things will probably happen if you do that. :)

I'm not sure how feasible it is to prevent that syntactically, so we'll
probably need to do a runtime cycle check.

I don't think there is a solution at compile time. Due to the dynamic
nature of the language.

Well the easy solution is to change the behaviour in complied/VM.
Currently, super is expected to be null to express parenting to Object. Why
not ditch that, and make a real parenting to Object and make Null trigger
an error in the VM at runtime.

**Comment by munificent** [comment]
> I'm thrilled by the idea of duplicating all of the code for every class declaration just to support a really unusual edge case, either, though.

Oops, I meant *not* thrilled here. :)

> Currently, super is expected to be null to express parenting to Object.

Is that still true? I thought we fixed that a while back. The compiler now has:

```c
  // Load the superclass (if there is one).
  if (match(compiler, TOKEN_IS))
  {
    parsePrecedence(compiler, PREC_CALL);
  }
  else
  {
    // Implicitly inherit from Object.
    loadCoreVariable(compiler, "Object");
  }
```

Either way, I my worries about circularity are unfounded. I should have run that example before commenting. :) Since the class hasn't been created yet at the point in time that its superclass is resolved, the superclass is `null` and that indeed triggers a runtime error since `null` isn't a class.

**Comment by mhermier** [comment]
I considered various solution like code duplications, code reorganisation etc...
And I found one that sounds reallistic and *cheap*, thought I don't know how costly it could get at runtime.
The idea is to introduce a ObjBindedMethod object, that would map a ObjClass* and a OblFn*. When hitting that object, the vm would offset corresponding opcodes.
So we remove the need to patch the code, so it can be reused as many time as required, at a pretty low memory foot print, and I hope a low speed cost since it will only affect a small subset of the opcodes (according to wrenBindMethodCode)

**Comment by skybrian** [comment]
Yeah, you're guessing on whether moving the calculation to happen at runtime affects benchmarks. I'd be guessing too. But it seems worth doing the experiment?

Alternately, since this is a rare corner case, something like this might work:
- The first time the class statement is executed, patch the code and remember the offset used.
- On each subsequent time the class statement is executed: check if the offset is the same. If it's different, make a copy, undo the offset and redo it.

That way, only rare programs (like the one I came up with) would take the hit on copying the opcodes.

**Comment by mhermier** [comment]
I also considered that solution, but I *rejected* because of the foot print
and the complexity cost of implementing the ObjFn duplication, and costly
it would be to make it efficient. But if my idea fails, it will probably be
the way, but will take quite time and energy to do it.
