### ISSUE TITLE
stopping VM instances from the host side

### ISSUE THREAD

**Issue by ghost** [wren-lang/wren#478]
Consider an infinite loop.

Maybe it would stem from a malicious "joke" mod the user downloaded, maybe from the user himself when trying to create some macro script or whatever.

In that case you'd probably be able to shut down your application/game gracefully, which by extension would mean stopping the blocking VM instance. By gracefully, I mean really anything from _not blocking execution at all_ to _stopping a level, showing an error message and going back to the main menu_ to _closing the application without crashing the window manager in the process_.

Apparently, some ways to implement this (but probably not limited to) are:

- Not at all. CLua for example doesn't seem to have something like this officially. Inofficially you can somehow abuse some debugging hooks and some error flag, with a couple of drawbacks.
- Having an official stop flag/method. AngelScript for example lets you call an abort method from a watchdog thread.
- Having a loop limit. This seems like a tacked-on solution in most cases, but I believe UnrealScript did this.
- Outsourcing the interpreter loop and letting the host application execute a couple of instructions each update cycle incrementally. Jynx and Papyrus VM (from Skyrim/Fallout 4) do this. I'd guess this allows for the easiest implementation of latent functions.

Some of those possibilities have probably drawbacks like reduced instruction throughput and some probably can't  be realized from the main thread, which probably rules out stopping the VM manually by GUI.

That being said, I didn't find anything like it in the documentation. What is Wrens take on this?

**Comment by mhermier** [comment]
AFAIK, wren VM is single threaded and don't support instrumentation from an external thread.
And there is no simple solution to this halting/suspend problem, since most of the solutions can lead to memory leaks.
Maybe the more interesting solution is a stop flag/count. That way, we should be able to perform debugging and stepping, that are also crucial for creating debugging tools.

**Comment by underscorediscovery** [comment]
Keep in mind that we've already implemented debugging with stepping and will be upstreaming it soon. You wouldn't typically want debugging support enabled for something like user facing mods though because it will cost performance, but also because it will also be able to introspect state, view module sources (if string based) and such.

You could probably put an external mutex around vm->fiber->error and set it that way which will stop the vm loop from what I see.

**Comment by mhermier** [comment]
Nice I wait to see stepping in action, and try to do a debugger *yummy*.

It is not really possible to do so, because if the user decide it is ok to infinite loop and we might need to be able to resume. So I really like to see how is your implementation of stepping, and its impact on speed.

**Comment by underscorediscovery** [comment]
I put a link to the video in the above comment but since thread is a different topic best to discuss the debugger in it's own thread when we post soon.

**Comment by luodaoyi** [comment]
Hi,  I want a Hook interface like lua script  "lua_sethook" 

``` c

...
lua_sethook(luaVm, Lua_YeildHook, LUA_MASKLINE, 0);
....

void Lua_YeildHook(lua_State* _L, lua_Debug* ar)
{
	if (bStop) {
		lua_yield(_L, 0);
	}
}

```
