### ISSUE TITLE
Suggestion: Constants

### ISSUE THREAD

**Issue by nanaian** [wren-lang/wren#503]
Wren constants would be nice, both for performance and cognitive reasons:

```js
var a = 2
a = 3

const b = 2
b = 3 // error
```

Many languages are being to gain language-level constants - JS and Rust, for example. Especially with wren's first-class-function support this'd be great for FP. Thoughts?

**Comment by maxdeviant** [comment]
@heyitsmeuralex I think in your example it should say

```c
const b = 2
b = 3 // error
```

:sweat_smile:

**Comment by jclc** [comment]
Enums too, while we're at it

**Comment by Akaricchi** [comment]
>Even constant folding is hard because a top-level constant may be referenced inside a method body before the definition of the constant has been compiled.

@munificent, I've actually implemented constant folding in my local fork, and so far it seems to be working. The way I did it was to mark a bunch of primitive builtins "pure", which means they:

1. Never modify state.
2. Always return the same value for every receiver/parameters combination.
3. Can be invoked at compile-time.

Every time a method call is emitted during compilation, I check whether the receiver and all the arguments are known constants and whether the method is a pure primitive, and if so, I call the method at compile time and patch the bytecode to remove the call, and emit the return value as a constant instead. I did not bother with purging the intermediate constants that may no longer be referenced by anything, though.

Would you be interested in a PR? Or is there a problem with my approach that I'm missing?

**Comment by munificent** [comment]
That handles constant folding of constant expressions with immediate values, like:

```
1 + 2 + 3
```

(And it's a neat solution to doing that. Good idea!)

But it doesn't work for constant folding *references to named constants*. The initial description of this bug is that constant declarations would help for performance, as in:

```
class Bar {
  method() {
    System.print(Foo + 2) // <-- Constant fold here.
  }
}

const Foo = 1
```

But the compiler can't easily constant fold that expression because we don't know `Foo` is a constant until after we've compiled the body of `method()`.

**Comment by munificent** [comment]
> Could we consider that an error @munificent? Referencing foo before var foo = "defined" would error, so why wouldn't const Foo?

No, we don't want to error on forward references to top level identifiers because doing so would break mutual recursion between classes. We want stuff like this to work:

```
class Odd {
  next { Even.new() }
}

class Even {
  next { Odd.new() }
}
```

In general, users tend to subconsciously expect that the order of top level declarations doesn't matter much — aside from actual top-level *imperative* code — because that's how it works in most statically-typed languages and even in most scripting languages.

**Comment by jclc** [comment]
Could constants have a requirement of being defined before being referenced? I'm certainly not in favour of forward declarations Wren.

**Comment by munificent** [comment]
> Could constants have a requirement of being defined before being referenced?

They *could*, but now we're talking even more complicated semantics. More complex to implement and more complex for users to reason about.

**Comment by Akaricchi** [comment]
@munificent right, but IIRC what you're describing is called constant propagation (related but different thing). That would be indeed harder to implement (and maybe indeed infeasible for Wren). However, I believe folding of simple expressions is a worthwhile improvement on its own, even if there's no propagation. Would you consider merging that if I open a PR? Asking because I'd have to do a bit of extra work separating it from the other changes in my fork that interact with it.

>But the compiler can't easily constant fold that expression because we don't know Foo is a constant until after we've compiled the body of method().

A workable solution (or hack, depending on your point of view) is to simply fold if and only if the compiler knows for sure that Foo is a constant at the time. Otherwise, just compile it into a regular reference. This does introduce an inconsistency to the semantics, but:
* it's relatively easy to implement
* it's invisible to users who don't care about such optimizations
* it satisfies those who do

>In general, users tend to subconsciously expect that the order of top level declarations doesn't matter much — aside from actual top-level imperative code — because that's how it works in most statically-typed languages and even in most scripting languages.

FWIW, having been programming in C almost exclusively for a while now, I subconsciously expect that it *does* matter at this point. Biased, I know, just my 5 cents.

As an aside, may I suggest `let` instead of `const`? Less keystrokes, same character count as `var`, and some other languages also use it this way.

**Comment by underscorediscovery** [comment]
> Otherwise, just compile it into a regular reference. 

any inconsistency like this in behaviour is really not a good ideal and not worth it imo :) We've probably all dealt with languages that give you a false assumption about something (like performance characteristics of a piece of code), only to find out later when debugging or profiling that the compiler has broken the assumption, which ruins your system/design/code/performance and in turn ruins your day.

I like the idea of constants too, but unless they're being used to a fuller extent they don't seem to pay their way and just seem to add unnecessary gotchas and stuff.

**Comment by jclc** [comment]
> As an aside, may I suggest let instead of const? Less keystrokes, same character count as var, and some other languages also use it this way.
I haven't seen `let` being used for constants in any language, only as an equivalent of `var`. I believe that would only cause horrible confusion that is not worth saving 2 keystrokes for.

**Comment by Akaricchi** [comment]
>I haven't seen let being used for constants in any language, only as an equivalent of var. I believe that would only cause horrible confusion that is not worth saving 2 keystrokes for.

From the top of my head, Swift uses `let` for constants and, like Wren, `var` for variables. I also thought ES6 does that, but I got confused apparently (it uses `const`, and *both* `var` and `let` for variables with slightly different semantics). Can't recall any other examples right now.

Alternatively, there's Scala with `val` for constants ("values") and `var` for variables.

**Comment by SinisterSoft** [comment]
The gideros version of Lua implemented constants by having code macros.  So code can be replaced when code is passed to the bytecode compiler.   It seems to work really well, perhaps the same thing could be added to Wren?

http://docs.giderosmobile.com/reference/enhancement/macroconstants#Macro%20Constants
