### ISSUE TITLE
Vector and matrix math as an optional module

### ISSUE THREAD

**Issue by jclc** [wren-lang/wren#504]
Since one of wren's primary use cases is to be used in games, it would make sense to have some basic vector/matrix support, probably something like a lite-version of glm with your basic vec2, vec3, mat3 and mat4. Swizzling becomes an issue though, if that even is desirable.

**Comment by munificent** [comment]
This isn't a bad idea. You can write a decent one in pure Wren, but the performance would probably be notably better in C.

**Comment by jclc** [comment]
Yep, I've made a simple Wren implementation for vectors already. After thinking about it for a while, swizzling doesn't really seem that useful at all outside of shaders anyway. I'd love to work on an optional C module, but I'm a little lost on how to make a write a built-in module.

**Comment by Akaricchi** [comment]
This is a bit offtopic, but you may find it interesting nonetheless. I've hacked native support for C complex numbers into my local copy -- I actually require that feature, because the game I hope to eventually integrate Wren into uses them very extensively.

Since you can't really stuff two doubles into one, I resorted to implementing them with objects first. Unfortunately, the complex math performance ended up being over 2 times slower than that of regular `Num`s. Later on I have disabled NaN tagging, and instead of encapsulating complex numbers in objects, I simply had them stored directly in the `Value` struct. The result of this was a 35~40% performance improvement over the original implementation. Note that in both cases, the actual methods were implemented in C, and in the same way. The `Value` size increase didn't seem to affect the other benchmarks, although the absence of NaN tagging itself did, of course.

If your Wren scripts spend a lot of time doing vector math, this approach might be worth a try at least. But it's probably too hacky for upstream Wren.

**Comment by bjorn** [comment]
@Akaricchi Why couldn't NaN tagging be used to determine whether a value was a complex number? Are there no bits left?

**Comment by Akaricchi** [comment]
@bjorn yes. I'm using values of type `double _Complex`, which are the size of two doubles, so obviously that wouldn't fit. Even if I sacrificed precision and used `float _Complex` instead, they'd still take up exactly the size of a double.

I'm considering another idea now: that is, changing the the Wren "native type" from `double` to `double _Complex`, and using NaN tagging within that. Then complex numbers wouldn't need a tag, what is now a `Num` would just be a special case of a complex number with the imaginary part set to +0, other types get NaN-tagged in the real part (assuming it's stored first) and get to use the extra bits from the imaginary part as a bonus (so that 64bit integers are possible, for example). However, I'm not sure of how portable this is and whether the performance will be as good. But it's pretty easy to implement so I guess I'll try it soon enough.

**Comment by ruby0x1** [comment]
While a reasonable idea, it's not something we'll be pursuing immediate term!
