### ISSUE TITLE
Stream source into the compiler instead of loading all source into memory?

### ISSUE THREAD

**Issue by jockm** [wren-lang/wren#537]
There needs to be a way for the enclosing program to feed wren source into the VM one line at a time.

Perhaps there could be a version of `wrenInterpret()` that passes in a function that gets the next line.  This way source could come from a filesystem, downloaded  in some way, streamed over a serial port, etc; without the need to hold all of the source in memory at once

**Comment by rljacobson** [comment]
Better to separate compiling to bytecode and running the bytecode. The vm should take a BytecodeStream, the bytecode compiler should take a StringStream, and there could be multiple sources for that string stream, e.g. A file, the internet, the cli....  

This design also makes it almost trivial to support serialization of bytecode to and from disk and paralellize bytecode compilation and optimization with interpretation.

**Comment by mhermier** [comment]
While true, it has 2 major flows:
- it adds a lot of non generic code.
- it is incompatible with at least current compiler implementation.

Making everything stream aware means either every task is *pausable* either
by stopping its work and returning control, or given control to the stream
and wait for it to return.

Since libuv was chosen, so the returning control design should be choosen,
but it is incompatible with current compiler implementation. Giving control
design is as much black magic as wren fiber switching, and implies pausing
execution witch implies threads and brings even more complexity.

Changing compiler is a long term viable solution, but require a lot of
effort (in C), because it requires a lot of complexity. (In my fork, I'm
currently taking a lot of time preparing wren parsing in wren to achieve
langage bootstraping in the long terme, and be able to deal with these kind
of needs).
