### ISSUE TITLE
Sandboxing API for running untrusted code

### ISSUE THREAD

**Issue by octacian** [wren-lang/wren#571]
As a precursor, if this feature already exists, sorry about the issue - I'm not yet very familiar with Wren.

Is there any chance of sandboxing being implemented in Wren? In particular, similar to [how it exists in Lua](http://lua-users.org/wiki/SandBoxes). This would make it possible to safely execute Wren code from another Wren script, in such a way that errors could not halt the whole program, RAM usage could be controlled, infinite loops could be made to time out (although a better way of handling this would be to run the unsafe code in a different fiber, IMO), and the APIs to which the code was allowed to access could also be controlled.

If that doesn't quite make sense, here's an example of how I'd imagine such a feature might work (please excuse any syntax errors, as I mentioned, I'm very unfamiliar with Wren):

```dart
// Create an environment providing a list of allowed and
// disallowed features. It would, however, probably be best
// to implement in such a fashion that the list was really a
// whitelist or a blacklist and only an array were provided.
var env = Environment.new({
    "import": true,
    "Fiber": false,
    // etc...
})

var code = "System.print('Inside an environment!')\n" +
    "var fiber = Fiber.new { ... }" // <- This would fail

var success, message = env.run(code)
```

**Comment by bjorn** [comment]
See #533 for a discussion related to your topic, since along with limiting API access you mentioned controlling RAM usage and infinite loops, both of which are things better implemented by sandboxing the whole process.

**Comment by octacian** [comment]
Why was this (and the other issue mentioned) closed? Based on the commit history from the last year and a half neither issue seems to have been solved, although I can't guarantee I didn't miss a PR as I didn't check the description of each.

**Comment by underscorediscovery** [comment]
Just cleaning up issues in general. I was tidying up many at the time, one or two that needed context slipped by. I'll add some details here.

The other thread mentions this part which I think is sufficient in that context. The rest of the thread goes on in more detail as to the complexity and difficulty.
> In general, I don't think it's a good idea for Wren to be in the business of providing security guarantees.

With regards to the script side environment, I like the idea and have used it in lua for a game before. One of the tools in lua to do that, is the override of `require`, which in the context of Wren is `import`.

Wren import is already controlled by the embedding application, as is the entire API available outside of wren core. So it's already possible (and I already do it) with Wren to base it on an inclusive list or exclusive list. 

The main distinction is the environment being defined on the script side vs native, but I think there's a few ways to achieve similar on the embedding side already if really desirable. What I will add is personally, I don't find [this kind of redundant forwarding](https://stackoverflow.com/a/6982080) elegant or efficient. It was the worst part of making a sandbox for the game, because every time you add something, you have extra busy work to make it show up in mods. Finally, it's also not possible with how Wren works, because while you can forward types, you can't forward methods. i.e `Math` vs `Math.min`. 

With regards to tight control over the wren core API, I can't see any APIs that need sandboxing since the core is pretty minimal. It seems that the use case for such a limited version of the language that lacks the core language, wouldn't be a useful version of Wren to expose. However, [since the core is exposed implicitly in the code with only a few lines](https://github.com/wren-lang/wren/blob/master/src/vm/wren_vm.c#L452-L461), and is trivially hackable, that's where my suggestion would lie. If you really wanted to do that, it would be reasonable to modify the implementation to do so. At this time, the use cases don't seem to fit the main Wren implementation for that specifically.

And lastly, for the code side, the other thread has some nuance to add. You already mentioned running the code inside of it's own fiber, this is a must and would prevent any errors from taking down the calling code. Infinite loops are a different story, and _right now_ I don't see a compelling use case for instruction limits, as the other issue discusses. Process based and thread based VMs with explicit external control is the most sound in general.

It's possible we can revisit this in future (and I've tagged it as such) but right now Wren continues to want to be minimal, and given the above trade offs, and how far you can already get as is, I'm feeling like there's not much to do towards this _right now_.

Thanks for bringing it up!
