### ISSUE TITLE
Calling Wren from C: How to handle when a receiver doesn't have a method

### ISSUE THREAD

**Issue by avivbeeri** [wren-lang/wren#574]
I'm building a game engine with Wren, implementing and executing with a core `Game` class.

I want to get a handle to the `update()` method, if it exists and hold it for the life of the program. 
Is there a way to test from C whether a receiver (the game class) contains a method?

**Comment by munificent** [comment]
No, there isn't. There isn't an easy way to do that from within Wren currently either. You'd basically need to create a fiber and in there try to call the method and check to see if running the fiber fails.

In general, Wren doesn't have much in the way of runtime metaprogramming. I'm interested in expanding that somewhat, but I want to be careful because that kind of functionality tends to harm performance and optimization to a greater degree than it provides value in return.

Can you give me some more details on why you want to dynamically check for this? Do you not know whether or not the class has this method? Having concrete use cases will help us design a better metaprogramming API.

**Comment by avivbeeri** [comment]
Sure :) I'm building a little micro game engine and it relies on the developer providing a Game class, with static `init`, `update` and `draw` methods. I'd like to make it so those hooks are optional. 

For example, there might not be anything to initialise, so the hook may not be defined. At the moment, if the user doesn't provide an `init` method, the `wrenCall` method gives a runtime error, which doesn't look so good.

**Comment by Akaricchi** [comment]
Can't this Game class inherit from a BaseGame class, which would provide empty stub implementations for those optional methods?

**Comment by avivbeeri** [comment]
According to the documentation, static methods are not inherited, so this
wouldn't work surely.

Even if it does, I'd rather not put the additional syntactic burden on the
end user to remember to inherit from a base class.

**Comment by underscorediscovery** [comment]
Aside from stub implementations, another typical use case of this pattern is reducing overhead. if you have 20 objects and only 1 of them is using the update function, or the init function, [you can spend a lot of time doing nothing useful](https://blogs.unity3d.com/2015/12/23/1k-update-calls/). You could keep a list of objects needing them and only ones that actually have it are called, by checking at load time.

One different approach, wren has nice syntax for block functions. For example,
```
update {
  ...
}
```

This is actually calling a method called update, which registers/adds the callback to a list somewhere. The exact usage can vary by your design needs but it sort of an all birds one stone solution.

**Comment by avivbeeri** [comment]
The use of a top level function is intriguing, but won't there be a similar
problem if the user hasn't defined one?

**Comment by underscorediscovery** [comment]
well, in this case it is your engine providing a way to get called back, on some event (init, update, etc). So the update method is defined by the engine, not the user in my example. 

It could be done in a few ways. One is inherited, which requires a few more steps for the user. One is a static method like `Game.update { }` but this can be inconsistent and lacks local variables. It might not fit your needs at all :) It all depends on your needs/goals.

I mention it because of the simplistic block syntax, you can get a simple approach that calls a function, inside of which you can add the callback to a list. If you can find a way to leverage that it's one option.

```
var Updates = []
class Game {
  static update(fn) { Updates.add(fn) } 
}

//on tick
Updates.each {|fn| fn.call() }
```

**Comment by mhermier** [comment]
I would do more somthing like this:
```
class Game {
  static new() {
    if (__updateCallbacks) __updateCallbacks = []
    this
  }
  static onUpdate(fn) { __updateCallbacks.add(fn) }
  static update() { __updateCallbacks.each {|fn| fn.call} }
}
```
And lie to the user to use:
```
var game = Game.new()

game.onUpdate {
   ...
}
```
That way is more future prof if tomorow you need to have more than one Game object.

Even more I would separate it completely, and have this logic inside of a (possibly private) object, and make this object call Game methods. That object would be named something like Engine and would be the *only* interface with the system. And make Engine call game updates and stuff.

**Comment by avivbeeri** [comment]
Interesting ideas. I'll consider this approach. How would you implement a
private object?

**Comment by mhermier** [comment]
By private, I meant a regular object not documented to the public API.
There is also a possibility to make a class from scratch in C so that it
does not appear in wren code, but requires access to internals.
