### ISSUE TITLE
Calling function from one VM whilst inside another

### ISSUE THREAD

**Issue by 0xen** [wren-lang/wren#602]
I am wanting to run multiple wren VM's at the same time as they will each be a component in an ECS (Entity Component System). I need the ability to send and receive messages between the Wren modules either by calling the VM function endpoints directly or going through c++ to broadcast a message to all VM's. I am aware that I can do the latter but calling function endpoints directly seem's to be a mystery. 

I have looked into using Modules but this would require a central Wren-based file to call each other Wren script files whereas I am wanting to have multiple files that can be loaded in and out dynamically whilst having the ability to call one and another.

Is this possible with the current library or would I need to do some wired Wren -> C++ - > Wren communication between components?

**Comment by mhermier** [comment]
In it's current form, I would not suggest to run multiple VM. It is know to
work to some degree of confidence. Some modules might be not well isolated.
In particular, with the io modules.

If you don't use the modules from src/modules you should be safe though.

That said, there is no such facility (yet). And the solution also differs
depending on how you run the VM hive, and the type of message you want to
send. and you have to serialize somehow the data, to avoid passing data
across VMs.

Basically, you need to write your communication bus as a module if you need
wren to send/receive messages. You might need that for complex
interactions, with threaded VM hive. But you have to be careful on what you
allow to be shared.

Differently, you only need to make dumb call to wren all iterating all the
VMs if you simply need them to react on *interrupt*. This is basically what
you want when you simulate multiple agent, and wake them up on each frame
of the simulation. And calling native modules might represent some sort of
communication, by replicating external data across the hive.

There is one extra possibility that needs a little of hacking, instead of
having multiple VM, is to have multiple *anonymous* modules. This is a
different approach, but since modules are isolated, you create
communication via libraries since there is no real way (for now) to
reference an anonymous modules.

I would not suggest you to do wren -> C -> wren calls as this, unless the
first wren is the coordinator and the last one can't communicate back.
While possible the message/event system solutions seems more reliable.

**Comment by underscorediscovery** [comment]
>with the io modules.

io is from the CLI and not the VM, right? The VM itself however is all self contained state and therefore multiple VMs would work just fine (minus automatic communication between them.)

**Comment by mhermier** [comment]
Yes, the VM in itself is self contained. There is no global variable I can
think of.

The IO cli module contains a bunch of them.

**Comment by underscorediscovery** [comment]
Closing this out as the answer to the original question is: there is no automatic communication of any kind, you need to do it manually.
