### ISSUE TITLE
Is it possible to use the VM without the compiler?

### ISSUE THREAD

**Issue by TimoRoth** [wren-lang/wren#625]
We'd like to use the VM on a _very_ memory constrained arm embedded board (namely a bluepill board).
Right now even an -Os build is a few kB too large to fit, and we kinda need other code as well.

So I was thinking, is it possible to get only the VM, and compile the code to bytecode elsewhere, and then only send the bytecode to the VM? That would get rid of quite a lot of embedded strings for the .wren files, and reduce code size as well.
Right now it doesn't look like it's prepared for that, as I can't find an easy way to write and load bytecode, or did I miss some API for that?

**Comment by mhermier** [comment]
No this is not possible with the project in it's current state for various
reasons.

**Comment by Leowbattle** [comment]
What reasons?

**Comment by TimoRoth** [comment]
We're on a very space and ram constrained device, with only 20kB RAM and 64kB Flash. So saving memory is a concern.

**Comment by mhermier** [comment]
The VM does not have a way to export/import byte code as this. This has to
be done. (Quite complex since you need a way to create a binary blob, and
because as this the language requires some opcode patching, so it can't
reside in rom at execution)

The language implementation as this, implies that you have a copy of the
source along with the bytecode for debugging purpose. (Relatively simple if
you don't care about debugging)

Plus the things I might have forgotten.

**Comment by munificent** [comment]
Yes, like @mhermier says, the architecture of the VM doesn't currently support this. It's an entirely reasonable request, but not an entirely simple one. :)

The main challenges, off the top of my head, are:

* To some degree, this means committing to having a stable bytecode format. Right now, it is a luxury that we can freely change the bytecode instruction set without impacting any users because it's entirely an implementation detail of the VM. Serializing and deserializing bytecode exposes that. We could mitigate that by simply saying that deserializing bytecode generated by any previous VM is not supported, but users are still likely to try and get unpleasantly surprised when things break.

* Right now, the VM can safely assume the bytecode is valid since it generated it itself just now. So there is no additional code or runtime cost to sanitize the bytecode. If we allow it as an external input, it probably should be verified. Again, we could simply declare that we don't do this and it's on you to sanitize your input, but if a user doesn't do that, it could be a security hole.

* The compiler creates runtime objects during compilation. When it compiles a function or method, it actually eagerly creates the runtime representation of a function. When it compiles a literal, it creates the runtime object for the literal and stores it in the constant table. We'd need to write code to serialize and deserialize these instead so there isn't a coupling from the compiler to runtime.

* Likewise, when the compiler compiles a top level variable declaration or use, it immediately declares or looks it up in the runtime representation of the module. This is the hardest technical limitation. The compiler uses the runtime module object to tell which top level variables already exist and how to refer to them. This is important for making the REPL work since each REPL entry is compiled independently but can access variables from previous entries. Also, the embedding API allows you to interpret new code in the context of an existing module.

    To load bytecode, this coupling needs to be severed somehow. We could restrict things and say that you can only load pre-compiled bytecode for a new module. That simplifies the problem. Then it's just a matter of the compiler serializing out the top level variables it declares/uses.

* Assuming we do all of this, then we need to be able to compile the VM with the compiler removed, which is your ultimate goal. That will likely turn up other subtle bits of coupling. Figuring how to *test* this configuration is difficult too. Ideally, we'd run all of the language tests in this mode.

I don't think any of these are unsolvable, but it is a good bit of work and will add significant complexity to Wren. (As always, limiting complexity is a key goal.)

**Comment by CosDevelopment** [comment]
I do not know if this will help you. But you can spawn an instance of the vm in C. Maybe you can use the C instance of the vm that way you can just compile code through the C api.

**Comment by cszawisza** [comment]
This feature would be super awesome :) Compile code on a PC and send bytecode to a uC :D sweet.
