### ISSUE TITLE
Import variable renames: import "..." for (x as y)

### ISSUE THREAD

**Issue by IngwiePhoenix** [wren-lang/wren#637]
Hello!

I wonder if this would or could be possible? Basically I want to be able to rename variables in imports, so they do not clash with other imports. Imagine you have a couple of adapters for accessing a cloud storage, and both of those adapters are expected to expose `Initialize`, then this would become an issue:

```wren
import "adapters/Dropbox" for Initialize;
import "adapters/Azure" for Initialize;
```

But this would solve the problem:
```wren
import "..." for (Initialize as MyInitialize);
```

This would basically be just a matter of picking a different name for the copy destination of the variable, as those are actually just being copied off the evaluated exports into the importing fiber. So instead of copying `a` directly to `a`, we'd copy `a` to `b` instead - or rename the variable after it has been copied, if that would be easier.

So how about this?

Kind regards,
Ingwie.

**Comment by underscorediscovery** [comment]
I implemented this before over here if you'd like to try it locally in your version: https://github.com/wren-lang/wren/pull/464 - so it's definitely possible.

**Comment by mhermier** [comment]
I'm not a big fan of introducing the new keywaord "as", while we could 
use "=". That inverts the parameters orders but it explicits what is 
imported.

**Comment by IngwiePhoenix** [comment]
I wouldn’t mind using the assignment operator either - but, I would appreciate having a method to rename imports. :)

**Comment by mhermier** [comment]
I would appreciate if Sven was doing commits even some minor cleaning

**Comment by bjorn** [comment]
I really like the "as" keyword (it's not uncommon, either) and I think it has the added benefit of potentially enabling import of all exports without needing to explicitly mention them, as in:
```dart
import "adapters/Azure" as Azure

Azure.Initialize
```

**Comment by bjorn** [comment]
@underscorediscovery Yeah, that would be one possible implementation. The module level variables could be exposed by static getters of a class constructed from the module.

**Comment by mhermier** [comment]
While it is an interesting, I'm not sure it is viable because of the method
buffer explosion.

**Comment by bjorn** [comment]
> While it is an interesting, I'm not sure it is viable because of the method buffer explosion.

While I understand it's a little off-topic for @IngwiePhoenix, I'm interested to know where this limitation is seen in the code. I tried to look for it but couldn't find a method count limit so far.

I found a module can have 65536 variables:

https://github.com/wren-lang/wren/blob/4ebb99d27f8a19809ee8c150e04051cda3ba5caa/src/vm/wren_common.h#L78-L81

and that a class can have 255 fields:

https://github.com/wren-lang/wren/blob/4ebb99d27f8a19809ee8c150e04051cda3ba5caa/src/vm/wren_common.h#L109-L114

But fields != methods and these methods could use upvalues rather than fields. One of the tests is called `many_methods.wren` and defines a class with 1000 methods, so the limit seems high at least.

Anyway, if this feature is not supported it is of course possible to define this "module class" by hand in the module and simply use "for" to get it.

**Comment by IngwiePhoenix** [comment]
True, that would be a viable work-around too!

```wren
// adapters/Azure.wren
class Azure {
  Initialize { Initialize }
}

var Initialize = Fn.new { /* ... */ }
```

Something like that, right?

**Comment by bjorn** [comment]
@IngwiePhoenix Yeah, that's what I meant. Though, there may be a small difference here that those variables are not bound (which is also why you can define the class first). It means their value could change and I guess slightly worse performance due to the lookup.

**Comment by IngwiePhoenix** [comment]
@bjorn That is pretty much always the case - even in JS and other languages. It is a common issue.

```js
import X from "x";

// vs.
import {a, b, c} from "x";
```

Whilst `X` is actually `module.exports.default`, `a`, `b` and `c` are all just references to the respective members of `module.exports`. In general, this means that the references are more distinct and actually easier to track for tools like `terser` and other tree-shaking utilities. So - basically, you can't quite eliminate a small overhead here anyway.

**Comment by mhermier** [comment]
The limitation comes from the fact that all class share the same branle
layout.
So if you define 1000 different method names next classes will create
buffers for 1000 entries plus it's unique method names, and it goes on
iteratively. so next class might be 1005, next 1006... And this number
never never shrink.

SUPER and CALL opcode limits the number to a short. But even if there is
room, since the module will have to inflate the number of unique symbols
drastically, and even if you have the memory to handle that, it will make
performance even more unpredictable, due to caches misses, due to methods
explosion.

If we go that way, we might need to revisit the class method storage from a
linear to a (hash)map lookup, with the performance issues that it might
involves, or even change the way lookup is done.

**Comment by bjorn** [comment]
@mhermier Hmm, that sounds like a problem for any sufficiently large program, but in general I do not expect the number of members in module classes to be higher than those of the average class. You meant "branch layout"?

**Comment by mhermier** [comment]
It is a problem for any large project. This design choice was made for it's
simplicity and efficiency. But since the viable layout is common to every
class object, the more you feed unique pointer signature, the more you are
garanteed to hit a cache miss. If it becomes a real problem, as I said we
can try to mitigate map, but it has to be benchmarked to see if it does
really help.

I also have some doubts about the compiler to allow to call a capital
letter member, and I also wonder how to handle module methods shadowing. If
module as some 'path' getter method, and you define a variable 'path' what
would you expect 'MyModule.path' to return?

I don't say that this grammar solution is interesting, but the consequences
has to be thought. Likewise with a potential bulk import, like: import
"foo" for *.
It might be a detail, but how do you handle names shadowing? There is a
partial solution with the "as" or "=" syntax. But I can think of 2
solutions here:
- ignore already imported symbols, but that might be miss leading.
- allow mass renaming with something like: import "foo" for Foo* = *
But then that solution bring the question what would mean: import "foo" for
Foo*. Is it a wildcard import ...

It may be a little bit more verbose, but I would use the mirror module way.
So something like:

import "mirror" for ModuleMirror
var mm = ModuleMirror.fromPath("mymodulepath")

And add some direct accessing with:
mm["foo"] = bar
or:
mm.variables["foo"]

Since I'm sure there will be a need for a mirror API at some point
(debugging/unit testing/...), I prefer that solution than bloating the
compiler/language with complex import functionality. I don't say such move
is not interesting from a usability point of view, it doesn't grow the the
language a lot, but implementation with it can have huge consequences to
consider.

**Comment by mhermier** [comment]
Le dim. 9 déc. 2018 à 21:23, Thorbjørn Lindeijer <notifications@github.com>
a écrit :

> But since the viable layout is common to every class object,
>
> What is the "viable layout"?
>
Variable, typo from auto correction of my phone. Well it is an error
either, I mean that every class share the same vtable layout.

> I also have some doubts about the compiler to allow to call a capital
> letter member.
>
> In my test this does not seem to be a problem.
>
> If module as some 'path' getter method, and you define a variable 'path'
> what would you expect 'MyModule.path' to return?
>
> I don't understand this. The module class would have a member for each
> module variable. There can be only one path variable in the module.
>

I mean for now, modules don't have a concrete class. With that change it
will have one. As a consequence, it will be natural to be able to access
it's name/path. So how to handle the shadowing of the module class and
variable possibly overusing them.

> Likewise with a potential bulk import, like: import "foo" for *. It might
> be a detail, but how do you handle names shadowing?
>
> The module class suggestion is essentially a bulk import without a name
> shadowing problem. Indeed I would not suggest using a wildcard since your
> code might break without warning when a module introduces a new variable.
>
> Since I'm sure there will be a need for a mirror API at some point
> (debugging/unit testing/...), I prefer that solution than bloating the
> compiler/language with complex import functionality.
>
> I do not understand how this could be an "either / or" question. The API
> of this "ModuleMirror" is so syntactically verbose that I don't see it as
> an alternative.
>
It is an alternative in terms of functionality duplication removal. It
doesn't do exactly the same thing, but permit to access the modules values
in a *similar* way.

I don't say the original solution is not desirable or viable. I only expose
the basic problems I see for now.

>

**Comment by underscorediscovery** [comment]
Closing this discussion as it's mostly unrelated to the original topic. The topic in particular can be discussed here further or in #464
