### ISSUE TITLE
Wren for Swift

### ISSUE THREAD

**Issue by SafelySwift** [wren-lang/wren#645]
I have run wren code in c and I noticed that it is a bit slow. As Swift is now the go to language for many developers, it would be very helpful. Also, as I am developing a language called Swizzle and I want to allow string interpolation. If I could see wren in Swift it would be easier for me to understand.

**Comment by SafelySwift** [comment]
Sorry I’m new to github and I don’t know if this is the kind of thing to ask about.

**Comment by KyleCharters** [comment]
If I understand correctly, you are asking for the project to be rewritten in Swift? This will likely never happen. In Wren's case, there are a lot of benefits to using C.
Specifically:
- Incredibly simple to write bindings, as most languages with a ffi exclusively support c.
- We can fine tune Wren to be as performant as possible, something not always feasible in higher level languages. (Due to gc, costly abstractions)
- Highly portable, supports any target you can think of.
- And of course, keeping its binaries small.

That being said, feel free to write your own Wren implementation or Swift bindings. The source code has some amazing documentation, and c is a fairly simple language, so it wouldn't be all that hard to learn the language as you go along. Hope that helps.

**Comment by underscorediscovery** [comment]
And regarding performance, wren is an interpreted language running in a virtual machine, while swift is a native language. It's expected there's a difference :)
