### ISSUE TITLE
String/bytes confusion

### ISSUE THREAD

**Issue by walterschell** [wren-lang/wren#659]
I was trying Wren last week and the biggest problem I had was with manipulating binary data. String.byte yields a list of numbers which is less clean from manipulating from the C API, and does not have a clean way of going back to String. 

A proposal would be that a byte sequence should be either a first class object with a corresponding WREN_TYPE_BYTES that  wrenGetSlotBytes and wrenSetSlotBYtes operate on.

Alternately, the String class could be extended with byteAt() and byteCount() methods to enable
 extracting bytes with byte, not codepoint granularity.
Possibly it is doable but it wasn't apparent from the docs, if so, perhaps a more explicit example in the docs.

**Comment by underscorediscovery** [comment]
In the documentation for String you'll find the distinctions I think you're looking for!
Let me know if that's not what you're after.

http://wren.io/modules/core/string.html

>If you want to get at the raw bytes, call `bytes`. This returns a Sequence that ignores any UTF-8 encoding and works directly at the byte level.

**Comment by walterschell** [comment]
1: The documentation is unclear how to go from String.bytes back to and equivalent String
2: From the c_api, they type of String.bytes is WREN_TYPE_LIST and which implies it cannot be retrieved with getSlotBytes (if it converts for you this would be nice to see in the docs)

**Comment by walterschell** [comment]
To be clear, I was proposing that String.byteAt return a 1 byte String as opposed to a Number, or that String.bytes return a type that can be getted, and set via getSlotBytes as a char * and size_t

**Comment by underscorediscovery** [comment]
Ah I misunderstood, sorry about that.
For what it's worth, in my use cases I pass the string itself in (not string.bytes) and use `wrenGetSlotAsBytes` which I think is the intended workflow. Then setSlotAsBytes can return the same value.

It's interesting to consider a bytes type, I think the minimalist intention was that String doubles as both (since it's not zero terminated or anything, and the wrenGetSlotAsBytes asserts that it's a String too). So my assumption is that you shouldn't be passing the sequence in but the string itself.

for 1. I don't think script side there is a way back to string from bytes, aside from iterating and using `String.fromCodepoint(byte)` which, gives you a one byte string of the given Number. It translates the byte (0...255) as a codepoint so if you're dealing with literal raw bytes then you'll get random gibberish string but your contents should match as intended. I think a more direct fromBytes is interesting to consider.

**Comment by walterschell** [comment]
The following code
```
var seq1 = [255]
System.print("Seq1 %(seq1)")
var str1 = ""
for (byte in seq1) {
    str1 = str1 + String.fromCodePoint(byte)
}
var seq2 = str1.bytes
for (byte in seq2) {
    System.print("Byte: %(byte)")
}
````
Yields
```
Seq1 [255]
Byte: 195
Byte: 191
```

String works fine if all of the byte manipulation is done from the C API and Wren just holds onto chunks of memory, however if you attempt to construct byte sequences from Wren or manipulate them is where the problems start. I found the mismatch between the fact that String.count counts codepoints, but that the index operator indexed from byte offsets and did not only return codepoints or only return bytes unsettling. In particular my intuition from most languages supporting an index operator is that regardless of whether String prefers to deal with codepoints or bytes, the index and count operators should be linked and that the last valid index should be count-1.

In principle it should be able to add a Byte and ByteSeq foreign class instead of the core language, but it appeared not possible to create a class instance from a foreign method. Searching online yielded some references to the WrenVM not being re-entrant, so I'm not sure if its a design decision or on the roadmap to fix.

**Comment by munificent** [comment]
It is a little confusing trying to use a single type for both byte arrays and textual strings, but I think that overall it's worth it to keep the language and implementation smaller.

> I found the mismatch between the fact that String.count counts codepoints, but that the index operator indexed from byte offsets and did not only return codepoints or only return bytes unsettling.

I think the mental model to have is:

* Most methods defined directly on Strings return *opaque cursors* that point back into the string. They happen to be integer byte offsets, but that's an implementation detail you shouldn't rely on. What you can rely on is that you can take the value returned by, say, `indexOf()` and pass it back in to the subscript operator.

* If you want to work with a string as a raw byte array, call `.bytes` and use the resulting object.

* If you want to work with a string as a sequence of code points, call `.codePoints` and use the result. If you want to have constant time access to individual code points and the length, call `.toList` on the result of that.

That leaves an open question as to what happens if you iterate a string directly, instead of calling `.byte` or `.codePoints` and iterating that. It's basically a question of what the default should be. I think most strings contain text and it's a very common bug in other languages to write code that intends to work with code points but actually works with bytes or code units. That code then breaks when given a non-ASCII string. So iterating a string defaults to walking the code points. It can still do that relatively efficiently since advancing a single UTF-8 code point at a time is straightforward.

If that's what iterating a string does, then `.count` should align with that, so it does.

**Comment by walterschell** [comment]
> Most methods defined directly on Strings return _opaque cursors_ that point back into the string. They happen to be integer byte offsets, but that's an implementation detail you shouldn't rely on. What you can rely on is that you can take the value returned by, say, `indexOf()` and pass it back in to the subscript operator.

If indexing on a byte offset is the logical equivalent of casting a random memory address as an iterator and dereferencing it, then erroring on an index not on a code point boundary would make more clear that String index operator is dereferencing an iterator/cursor and not performing a offset based lookup more clear.  I'm not sure under what conditions a one byte string is a useful thing to return. In the case you wanted to display to the user that byte XX at offset Y is invalid utf-8, where would you have gotten offset Y from? 

Having the ability to read bytes via String.bytes implies that the user might want to manipulate byte sequences inside of Wren and not via foreign functions. Currently there is no way to build arbitrary byte sequences inside of Wren programatically, they must be constructed via foreign functions. Looking at the code a String.fromBytes, or String.fromByte constructor looks like it would be the most minimal modification.
