### ISSUE TITLE
Embedding API: passing user-data to finalizers

### ISSUE THREAD

**Issue by MarcoLizza** [wren-lang/wren#684]
When dealing with finalizers, sometime it might be needed to access the global (relatively to the current VM instance) `user-data`.

Passing the VM pointer is not an option, so I suggest to change/extend the current `WrenFinalizerFn` signature to include just the `void *` to the user-data.

**Comment by mhermier** [comment]
Chicken egg problem spotted. Instead it should be an allocator private data
pointer.

**Comment by MarcoLizza** [comment]
@mhermier, can you please elaborate a bit? Why it should be an allocator private data pointer and how, in the case, this should be done and appear?

**Comment by mhermier** [comment]
Depends on the level of granularity that it is required. But ideally you
want memory management to be self contained.

Having it merged in the main code looks to me to be a mix of consern.

Implementation wise, it doesn't change the signature, only the way private
menory manager data pointer is stored and abstracted.

The way you describe the user to create a function, to retrieve the
(optional) memory manager private data from user data. The way I propose,
is to make the configuration remember the private data, and use it
directly, eliminating one extra conversion layer, in case you might want to
use an memory manager like talloc directly.

**Comment by MarcoLizza** [comment]
@mhermier I think there has been a misunderstanding. I'm not suggesting the user (i.e. the Wren user/programmer) needs to provide a custom function/allocator/accessor to allocate/access some private data.

I'm just suggesting to change the `WrenFinalizerFn` typedef by adding in the signature an additional formal argument. Currently, when the foreign object is finalized the VM passes the foreign data (allocated in the constructor). In my opinion, the VM user-data (that the user could have configured) should be passed as well.

**Comment by mhermier** [comment]
This is exactly what I'm saying. Allocator and deallocate functions should
have a private data pointer. The only nuance I want to add is instead of
the user data, it should be allocator private data (which can be the same
as user data)

**Comment by MarcoLizza** [comment]
Got it, I mis-understood it. You were referring to the C-side object-allocator/deallocator.

It occurred to me that probably one could just store the needed "user-data" values during the object allocation and reuse it in the finalizer.

**Comment by mhermier** [comment]
If I remember well, it was already discussed and was ditched to match
malloc API interface. Maybe we should look the allocator API with realms to
see a possibility for this proposition?

**Comment by MarcoLizza** [comment]
The fact that one can't call in the finalizer the `wrenReleaseHandle()` for a `wrenGetSlotHandle()` reference obtained in the allocator is really unconfortable.

I implemented a (dirty) workaround for my own purposes, but I'm not happy with it.

Having the VM in the finalizer (and being it safe in releasing such a handle) would be definitely better. Any chance someone else would need this? Or am I the only one with such a need?

**Comment by mhermier** [comment]
Can you show a testing case code. I would like to see in practice how it
looks like.

**Comment by MarcoLizza** [comment]
@mhermier are you interested in the specific use of callbacks I'm referring to? Or in the workaround?

The latter was only possible since I'm implementing a game engine where I can periodically call garbage collection and keep track of the to-be-released handles. Otherwise, I wouldn't have been possible.

**Comment by mhermier** [comment]
I'm interested in seeing the use case and your solution. So I want to see
an example of it.

**Comment by underscorediscovery** [comment]
If you look at this differently, the foreign data _is already_ a user data pointer as far as the VM is concerned. 

One common concern with user data (for me) is it that it is a single value. For now, it sounds like you have a single handle to release, so the idea of a single place to stash it sounds good. But what happens when you have 2, or more handles? Or other data?  Your user data becomes a struct... so with this inevitability in mind, you can skip the middle step and store your foreign data in the same struct from the get go, and treat it as user data.

```cpp
struct MyType {
  float a; 
  float b;
};

//This is the struct used inside the foreign allocator, finalizer, and method callbacks. It is user data.
struct MyTypeData {
  MyType* type;
  WrenHandle* handle1;
  WrenHandle* handle2;
};
```

One thing you'll notice here is that the pointer `MyType* type;` inside this proxy struct can now be allocated outside of Wren GC if preferred (see #499 for a use case/discussion). If not a pointer, a POD type or placement new would be used to allocate it inside the GC (e.g using `MyType type` instead);

For now, I'm closing this as I am fine with the mechanics of the finalizers already, and this idea will impact the method callbacks as well as the finalizer. I'll tag it with `future`, as I think there's something interesting about more than one allocator callback (or at least, something like an allocator tag for pools, as discussed in #499).
