### ISSUE TITLE
Inheritance and Scope in Docs?

### ISSUE THREAD

**Issue by crystalsolenoid** [wren-lang/wren#691]
Is this how scope is supposed to work with inheritance?
```
class Parent{
	construct new() { _test = 5 }
	test { _test }
}

class Child is Parent{
	construct new(){
		super()
	}
}

var myChild = Child.new()
System.print(myChild.test) // 5
```

```
class Parent{
	construct new() { _test = 5 }
}

class Child is Parent{
	construct new(){
		super()
	}
	test { _test }
}

var myChild = Child.new()
System.print(myChild.test) // null
```
How do I work around this if I want to use fields initialized in a parent constructor in a child class? Do you just have to use getters and setters and then use super.test?

Maybe this would be expected behavior if I actually understood how Wren does scope, but coming from other styles of class inheritance it feels very surprising to me.

If this is the way it's supposed to work, could that be clarified in the classes documentation? None of the examples for super() use fields. It says that methods are inherited but static methods aren't. Since it says nothing about fields, I would assume that only static fields aren't inherited.

**Comment by mhermier** [comment]
What are you trying to achieve?
Anyway what you are trying to do looks like something like proxying instead
of subclassing.

**Comment by bjorn** [comment]
> How do I work around this if I want to use fields initialized in a parent constructor in a child class? Do you just have to use getters and setters and then use super.test?

From [the documentation](http://wren.io/classes.html#encapsulation):

"All fields are _private_ in Wren—an object’s fields can only be directly accessed from within methods defined on the object’s class. You cannot even access fields on another instance of your own class, unlike C++ and Java."

So yes, you need to define getters and setters to make fields available to other classes, including derived classes. You don't need to write "`super.`" though. Since methods are inherited they are readily available in the scope of the subclass (so, you only need "`super.`" if you have overridden the method but want to call the version of the superclass).

> If this is the way it's supposed to work, could that be clarified in the classes documentation? None of the examples for super() use fields. It says that methods are inherited but static methods aren't. Since it says nothing about fields, I would assume that only static fields aren't inherited.

Static fields are also private (though we can only deduce that from reading "They work similar to fields except the data is stored on the class itself, and not the instance.").

It's a bit confusing to talk about whether an instance field is "inherited". Each instance obviously has all the fields of its class and all its superclasses, so they are definitely inherited. But since they are private, you still need a getter and/or setter to make them usable outside of their class.

**Comment by crystalsolenoid** [comment]
Okay, so with Wren's level of class privacy, a derived class has no privileged access to its superclass' fields? They still exist, but isolated from the derived class unless you're using getters and setters?

I guess since all the languages I've used before haven't been this strict about class privacy, I've never even thought of the fields of the superclass being "out side of" the derived class. That's why the documentation "an object’s fields can only be directly accessed from within methods defined on the object’s class" didn't work for me.

Thanks for the explanation! I think I understand it now, but it might be worth it for the docs to clarify so others aren't confused.
