### ISSUE TITLE
what is the best practice to read wren source code

### ISSUE THREAD

**Issue by uxnow** [wren-lang/wren#700]
hello, friends! 

I love the style of wren, and really want to get involved.
I know the best way is to read source code first.
so what is the best practice?

thanks everyone!

**Comment by bjorn** [comment]
While it's possible to just jump in and read the source code, I would recommend going in with a purpose. Maybe there is a certain feature you like about Wren and you're wondering how it is implemented, then you have something to search for in the code and it helps to limit the scope to avoid getting overwhelmed.

You can keep looking at new parts to try to understand them, but since you'd like to get involved you'll soon enough be looking for something to change. If you don't have an idea yourself, go over the list of open issues to see if something connects.

And finally, don't be afraid to open a pull request with your changes. Even if it may not end up getting merged, that will be a chance to discuss the change and to get valuable feedback. This is where you'll become part of the community. If you like, you can also join the [Wren Discord](https://discord.gg/s5EpYPS) to chat with other people interested in Wren.

**Comment by uxnow** [comment]
thanks, @bjorn , I will try them!
