### ISSUE TITLE
Is it possible to merge the "functional" branch

### ISSUE THREAD

**Issue by paladin-t** [wren-lang/wren#711]
It would be great to use `func()` instead of `func.call()`.
I saw last commit to that branch is 4 yrs ago. Just wondering would there be a chance?

**Comment by underscorediscovery** [comment]
It's not a priority at the moment unfortunately. If I remember correctly there were many discussions around the issues with it, and call was decided on as the best option and has stuck.

**Comment by munificent** [comment]
It's been so long since I put that branch out that I'm honestly not sure how or even *if* it works. Given an expression like `foo(arg)`, how does it know whether to desugar that to `foo.call(arg)` versus treating as calling the method `foo()` on `this`?

That's probably why I stopped working on the branch. I think it's very likely a dead-end in the design space.

**Comment by underscorediscovery** [comment]
Side note, it [seems feasible](https://gist.github.com/zkiraly/c378a1a43d8be9c9a8f9) to tag and archive the old branches in a clean up pass. I'll take a look at that soon.

**Comment by bjorn** [comment]
> It's been so long since I put that branch out that I'm honestly not sure how or even _if_ it works. Given an expression like `foo(arg)`, how does it know whether to desugar that to `foo.call(arg)` versus treating as calling the method `foo()` on `this`?

Well, the branch is there so we can inspect it to get answers, right? I didn't try it, but I did find this comment:
```diff
+  // If a parameter list follows a resolved name, then it will be treated as an
+  // infix call operator on it. So "foo(arg)" gets parsed to "foo.call(arg)" if
+  // foo resolves to a variable and "this.foo(arg)" if we're in a class.
+  //
+  // This makes the *semantics* slightly context-sensitive but keeps the syntax
+  // context free: "foo(arg)" is always *meaningful* regardless of how "foo" is
+  // resolved, it just means one of two things.
```
So it appears there was no problem with turning it into a `foo.call(arg)` when `foo` resolves to a variable, and `this.foo(arg)` otherwise. To me this also seems pretty intuitive.

The branch also includes a change turning `var f = Fn.new {` into `fn f() {`, which I think is pretty nice as well.

Anyway, in the end it's up to the maintainer to decide what he wants to maintain, so I respect if @underscorediscovery prefers to archive this branch instead of merging it.

**Comment by paladin-t** [comment]
I also respect the maintainers' decisions. But just imagine, if someone was not only writing Wren code, but also making an auto code generator, it's intuitive to have this branch for calling generation.

**Comment by mhermier** [comment]
If I'm not mistaken this branch was ditched because it made the langage
more complex/ambiguous because of getters.

**Comment by munificent** [comment]
> If I'm not mistaken this branch was ditched because it made the langage
more complex/ambiguous because of getters.

That sounds right to me too. It's been a while since I've had this all loaded into my head, but that is the always the linchpin issue with allowing function call syntax in Wren.

**Comment by mhermier** [comment]
This also the same reasons why I think the += like operators can't be added
to the language. It adds a complexity that can only be efficient/simple
with a statically typed langage.

**Comment by bjorn** [comment]
There's of course a difference between something introducing actual problems, and something introducing too much complexity for your liking.

From my understanding of the `functional` branch, it did not actually introduce problems. To be sure one would just need to try it, but there's no point in guessing about it. Maybe I'm misinterpreting, but it sounds to me like there's a decision being made on guesswork.

Whether it introduces too much complexity, either in the implementation or in the definition of the language, is subjective but certainly also relevant. But if we abandon the change because of this then we don't need to argue for that decision based on guessing about potential issues.

> This also the same reasons why I think the += like operators can't be added to the language. It adds a complexity that can only be efficient/simple with a statically typed langage.

There's pull request #701 for that, where we can try to judge whether having those operators are worth the additional complexity. If you think it can't be added please provide more specific comments there.

**Comment by mhermier** [comment]
Le jeu. 5 déc. 2019 à 13:33, Thorbjørn Lindeijer <notifications@github.com>
a écrit :

> There's of course a difference between something introducing actual
> problems, and something introducing too much complexity for your liking.
>
> From my understanding of the functional branch, it did not actually
> introduce problems. To be sure one would just need to try it, but there's
> no point in guessing about it. Maybe I'm misinterpreting, but it sounds to
> me like there's a decision being made on guesswork.
>
> Whether it introduces too much complexity, either in the implementation or
> in the definition of the language, is subjective but certainly also
> relevant. But if we abandon the change because of this then we don't need
> to argue for that decision based on guessing about potential issues.
>
> This also the same reasons why I think the += like operators can't be
> added to the language. It adds a complexity that can only be
> efficient/simple with a statically typed langage.
>
> There's pull request #701 <https://github.com/wren-lang/wren/pull/701>
> for that, where we can try to judge whether having those operators are
> worth the additional complexity. If you think it can't be added please
> provide more specific comments there.
>
No, it is not the correct place either to discuss that, because both
problems are the same problem.

The fact these ideas implies the introduction of an undecidability of
symbol resolution at compile time, implies that one behavior should be
either resolved at runtime (increase of runtime complexity, meaning either
more assembly or introduction/hacking of opcode) or by baning some
interpretation.

The .call and getter syntax were put in place to resolve this situation by
baning the other interpretations.

The += syntax as the same issue, it can be either a call to an operator
overload or a call to the global operator, and since it can't be determined
at compile time, we have either to ban some interpretation or resolve the
situation at runtime.

If we to introduce += operators and want to be consistent with operator
overloading, then we should also have to also add the function syntax for
consistency and resolve all that mess at runtime. The other solutions are
either not allowing operator += overloading and warn the users about
inconsistency about the absence of overloading, or not introduce the syntax
at all.

>

**Comment by munificent** [comment]
> From my understanding of the `functional` branch, it did not actually introduce problems.

It does introduce real problems. Consider:

```
class A {
  foo { Fn.new {|a| "getter returning fn" } }
}

class B {
  foo { Fn.new {|a| "getter returning fn" } }
  foo(a) { "method 1" }
}

var obj
if (monday) {
  obj = A.new()
} else {
  obj = B.new()
}

obj.foo(1)
```

Overloading by arity is deeply ingrained in the language and is one of the things that makes it simple, fast, and expressive. You get some level of overloaded dispatch essentially for free because the dispatch can be done at compile-time based on syntax. If we add function-call syntax and also allow getters, the compiler loses the ability to tell if `obj.foo(1)` means "call the method `foo(_)` on `obj`" or "call the *getter* `foo` on `obj` and then function-call the result".

In tricky cases, like the one here, it's not even clear at *runtime* which operation should be performed.

Self-assignment operators are straightforward compared to that.

**Comment by mhermier** [comment]
> Self-assignment operators are straightforward compared to that.
>
Wrong, consider:

class Foo {

   + (other) { ... }

}

class Bar is Foo {

   += (other) { ... }

}

var obj = Bar.new()

obj += 42

should it performs foo = foo + 42 or += 42 from Bar. It is the same 
problem disguised, it is a (as what I can best would describe it as) 
partial symbol resolution problem.

For both problem the *saner*/only fix seems to lookup the target and try 
to dispatch depending on the presence of symbols. For the call it should 
be something like (taking your example) in pseudo code:

if obj.hasMethod("foo(_)") then

   call("foo(_)", obj, 1)

else

   call(".call(_)", call(".foo", obj), 1)

end

Likewise for my example it is:

if obj.hasMethod("+=(_)") then

   call("+=(_)", obj, 42)

else

   obj = call("+", obj, 42)

end

Both behavior should be either reflected in assembly or embedded in 
opcode. The thing is that function code in practice affect nearly every 
symbol resolution that could be evaluated with parameters, while 
assignment operators are more restrained. But it stays the same issue, 
to solve it you have to perform at runtime a method lookup to choose a 
behavior. This is how, at least, I knew it was going to be costly.

This is why I don't really like the fact that self assignment operators 
to be integrated. It will (re)open the "runtime symbol resolution" can 
of worms, unless we add a huge bunch of restrictions (that will probably 
not be satisfying users, or at least me because I won't be able to do 
"var a = List new \n a += 42" correctly and efficiently).

**Comment by bjorn** [comment]
> If we add function-call syntax and also allow getters, the compiler loses the ability to tell if `obj.foo(1)` means "call the method `foo(_)` on `obj`" or "call the _getter_ `foo` on `obj` and then function-call the result".

Right, as far as I understood, `obj.foo(1)` will always call a method `foo(_)` on `obj` since `x()` can only be interpreted as `x.call()` when `x` is a known variable, which `obj.foo` never is.

So I think there are no real problems with the disambiguation, but the question is more about whether it really improves the language given this approach to disambiguation. I think this minor convenience for function calls comes at the cost of readability (the reader can have a harder time to disambiguate than the compiler), and I think that's a good reason to archive this branch.

> Wrong, consider: `class Bar is Foo {   += (other) { ... } }`

I think it's unfair to call it wrong with that argument because I don't recall overloading of these operators being an included goal. As far as I understood #701, `x += y` is being introduced strictly as syntactic sugar for `x = x + y`.

**Comment by mhermier** [comment]
Le ven. 6 déc. 2019 à 16:08, Thorbjørn Lindeijer <notifications@github.com>
a écrit :

> If we add function-call syntax and also allow getters, the compiler loses
> the ability to tell if obj.foo(1) means "call the method foo(_) on obj"
> or "call the *getter* foo on obj and then function-call the result".
>
> Right, as far as I understood, obj.foo(1) will always call a method foo(_)
> on obj since x() can only be interpreted as x.call() when x is a known
> variable, which obj.foo never is.
>
Probably, but you implement the idea to the user that it is doable, and you
will have to teach them why it can only be done in that context and not
other context. If you want to add that kind of feature you have to do it
fully or not.

For the record, (expr)(42) might not be ambiguous either.

But because of the getter syntax it will never be possible to generalize
it, and because of that I don't think it should be enabled here and there
for some unambiguous case.

> So I think there are no real problems with the disambiguation, but the
> question is more about whether it really improves the language given this
> approach to disambiguation. I think this minor convenience for function
> calls comes at the cost of readability (the reader can have a harder time
> to disambiguate than the compiler), and I think that's a good reason to
> archive this branch.
>
Wrong, consider: class Bar is Foo {   += (other) { ... } }
>
> I think it's unfair to call it wrong with that argument because I don't
> recall overloading of these operators being an included goal. As far as I
> understood #701 <https://github.com/wren-lang/wren/pull/701>, x += y is
> being introduced strictly as syntactic sugar for x = x + y.
>
The problem is to envision the future and the corner cases. Because adding
that syntactic sugar has implications to the language, and what users might
expect from it. Having arbitrary limitation without having tried to think a
little deeper is never a good thing, you'll end up with disappointments or
unfixable behaviors.

Don't get me wrong, if it goes in I'll probably use it, but the fact that I
can overload my own, makes it too much limited to be really useful too me.

>

**Comment by mhermier** [comment]
Another note for adding assignment operators, if we go the other way
around, that is allowing them generally in class, we add the functionality
and put the limitation only on immutable types which are basically string
and numbers.
And if user really need/insist on having them we can provides boxed types,
showing explicitly the extra costs of having them.

**Comment by farteryhr** [comment]
does `foo.()` look nice? eliminates ambiguity and saves keystrokes.
