### ISSUE TITLE
Inconsistent behavior: nonexistent class

### ISSUE THREAD

**Issue by buckle2000** [wren-lang/wren#747]
```
System.print(nonexistent)
var nonexistent
// Error at 'nonexistent': Variable 'nonexistent' referenced before this definition
```

```
System.print(Exist) // null (???)
class Exist {}
```

**Comment by buckle2000** [comment]
Also, fields in a class don't have to be defined. A single typo can ruin my day. Any idea on that?

**Comment by bjorn** [comment]
@buckle2000 In Wren, a lowercase name cannot come from the global scope. A lowercase name can only refer to a local variable (or parameter) or a class method. As such, the compiler can generate an error when it could not resolve it.

The same is not true for names starting with upper case, since they fall back to the global scope. In general, any code may have executed and could have set `Exist` before it was accessed (the compiler  can't know, it might have been in a different file or beyond the point the parser has reached). So it can't raise an error and at runtime you will know whether it exists or not, by checking if it is `null`.

> Also, fields in a class don't have to be defined. A single typo can waste several hours on debugging since uninitialized fields are `null`. Any idea on that?

Any usage of a field defines it (both reading and writing). I believe it needs to, because as soon as the field is used the compiler needs to assign it a location in the memory layout of the class (it's a single-pass compiler).

That said, I guess it should be doable to raise an error at the end of parsing the class definition, if any field was detected that is only ever read but never written to (and similarly, when a field is only ever written to, because that's not useful either).

**Comment by buckle2000** [comment]
OK, this is strange. This is definitely undocumented.

**Comment by mhermier** [comment]
I think it is documented, but there might be not enough highlight in
documentation about this unusual naming convention.

**Comment by bjorn** [comment]
Well, of course I didn't write Wren so my above comment should have come with a disclaimer and it may not be exactly what is going on. The behavior is documented in the context of the implicit `this`:

http://wren.io/classes.html#implicit-this

So, I'm actually not sure how this affects variables with uppercase or lowercase initial character outside of class member scope, but I expect it's related.

**Comment by buckle2000** [comment]
Should that be in the "variables" section?

**Comment by buckle2000** [comment]
Interesting. Since it's using a single-pass compiler, the class must be defined before used?

**Comment by bjorn** [comment]
> Interesting. Since it's using a single-pass compiler, the class must be defined before used?

No. The code defining the class has to have run before you try to instantiate it, but it may still be defined afterwards. This works:

```dart
var func = Fn.new {
    MyClass.new()
}

class MyClass {
  construct new() {
    System.print("MyClass.new")
  }
}

func.call()
```
It is because the compiler will insert a lookup for `MyClass` from the global scope when it compiles `func`, and by the time `func` is called, this lookup succeeds.

**Comment by mhermier** [comment]
This goes a little deeper, you can also name variables with a capital
letter to force late lookup.

**Comment by buckle2000** [comment]
Alright. I think the documentation of this behavior should be in another issue.
