### ISSUE TITLE
Should we check for undeclared methods on this at compile-time?

### ISSUE THREAD

**Issue by ChayimFriedman2** [wren-lang/wren#810]
Currently, the following code fails at runtime:
```wren
class C {
  construct new() {}
  
  f() {
    System.print(a)
  }
}
C.new().f()
```

As opposed to the following code, which fails at compile-time:
```wren
System.print(A)
```

Both class methods and top-level variables have similar semantics: they can be accessed before their declaration. While the compiler keeps track of all the top-level variables accessed and verifies at the end that all of them were declared, it doesn't do so for methods.

Should it? The advantage of that is like everything: we prefer to detect and reject errors as soon as possible, and with minimal user code executed as possible. The downsides are that this is not in-line with accessing methods on other objects (not `this`), and if we also want to detect `this.undeclaredMethod` (with `this.` prefix), we may be required to perform more work since in the current code the compiler does not perform any lookahead when meeting `this`.

My personal opinion is that the advantages are bigger.

**Comment by mhermier** [comment]
It should be pretty easy to add this check to the class compiler. While the class is parsed there is only a need to add unresolved symbols to a lists, and check at the end of the class definition. We can speed up the logic by removing unresolved entries when methods are added (and maybe using the method string that was unresolved).

**Comment by ruby0x1** [comment]
Don't forget about super classes which we don't have in hand at this point.

**Comment by mhermier** [comment]
Nice catch, so basically it is not possible to implement as this. It would require either a smarter compiler, or a more statically typed language.

**Comment by ruby0x1** [comment]
I did look into this a bit recently fwiw. Since there is a binding step that happens in bytecode after the compiler is done, where methods are bound and superclass is bound, bytecode is patched etc - the connection is not immediate during the compiler. This is one point where it can check, because it has access to the superclass and the list of methods for both, and is at bytecode runtime, but it still before any code is run. i.e this will catch errors even if the code path is never executed.

In this case of just checking if you used a name that exists, I think it would be possible but does involve quite a few mechanics. 
An import map, a `ClassInfo` map on a module etc. It gets trickier: 

`example.wren`:
```js
class A {
  example() { System.print("example") }
}
```
`forward.wren`:
```js
import "example" for A
```
`usage.wren`
```js
import "forward.wren" for A
class B is A {
  construct new() {
     example() //from superclass
  }
}
```

So in this case we can find the class we want by recursively asking the import map:
- `usage_module.imports["A"]` -> finds `forward_module`
- `if(forward_module.c;lasses["A"]) return A` else, finds `example_module`
- `example_module.classes["A"] returns A`
Then ask the class:
- `A.methods...`


But this isn't the full picture either: cyclic imports and also partial code state. 
Because you can import anywhere, it means that an import can happen in the middle of a module, so e.g all classes aren't compiled yet and the `classes` map is incomplete, and since you can import in a method, `methods` is incomplete too. 

So you can't do the check when compiling methods or even classes, it has to happen at the end of a module, or separate state, like at the end of wrenCompile.

**Comment by mhermier** [comment]
Effectively, the check could be done at binding. It could help to catch some errors.

Though, I'm wondering if we really want that feature. I mean, currently there is no proper way to create stubs/interfaces, and it will force to always have complete class/implementation. Not that it is a bad thing, but In some aspect it defeat the interest to have a dynamic language.

**Comment by munificent** [comment]
Yeah, this is just fundamentally not how dynamically typed languages work. You'll have a lot of difficulty making progress in this direction without either getting into a weird uncanny valley where the language feels inconsistent, or ending up going all the way to static types (which would be a monumental change).

In particular, it is a *feature* that you can call methods on a class that aren't declared. They're how you do abstract methods:

```
class Base {
  stuff() {
    System.print("Base stuff")
    // Let derived class do things too.
    onStuff() // "abstract" method call
  }
}

class Derived is Base {
  onStuff() {
    System.print("Derived stuff")
  }
}
```

**Comment by ChayimFriedman2** [comment]
I'm closing this issue now as this proved to be not possible. Not only imports and so, but also dynamic base class:
```wren
class C is func() {}
```
