### ISSUE TITLE
Do we really want to allow overloading `is`?

### ISSUE THREAD

**Issue by ChayimFriedman2** [wren-lang/wren#838]
Take this piece of code for example:
```wren
class C {}
System.print("123".replace(C, "haha"))
```
Fortunately, we get:
```
From must be a non-empty string.
[compile line 2] in (script)
```
But we're clever (or dumb?) programmers, so we look at `String.replace(from, to)` source code:
```wren
  replace(from, to) {
    if (!(from is String) || from.isEmpty) {
      Fiber.abort("From must be a non-empty string.")
    } else if (!(to is String)) {
      Fiber.abort("To must be a string.")
    }

    // ...
  }
```
Haha! We test for string existence using the `is` operator, and as Wren programmers we know that we can overload all operators, including `is`. So let's redesign our class:
```wren
class C {
  static is(other) { true }
}
System.print("1 2 3".replace(C, "haha"))
```
(If you wonder why `static is()`, this is my way to save me the need for constructor and creating and instance. See #797 for details).

Oops? We get:
```
C metaclass does not implement 'isEmpty'.
[compile line 4] in (script)
```
and the miserable programmer who we give this code to don't understand what's happening here.

If we replace the operands, things just get worse:
```wren
class C {
  static is(other) { true }
}
System.print("1 2 3".replace("non exist in source", C))
System.print("1 2 3".replace("1", C))
```
Now, when the string does not appear in the source, this works. But when it does, we get a mysterious error message:
```
1 2 3
Right operand must be a string.
[compile line 5] in (script)
```
Hmm, the culprit is here:
```wren
  replace(from, to) {
    // ...
      result = result + this[last...index] + to
    // ...
  }
```

Even more strange, if we use a method that was written in C, we _does_ get an error! Woo, we can now know which method was written in C and which in Wren! (Yeah. looking at the source is still better):
```wren
class C {
  static is(other) { true }
}
System.print("1 2 3".contains(C))
```
```
Argument must be a string.
[compile line 4] in (script)
```
Why, because C methods doesn't get through the process of calling the `is` operator.

In short, I don't see any reason to allow overriding `is`. It's a special operator and as such, needs its own bytecode. Overriding it just make things go **_really_** weird.

**Edit:** Here's what other languages do:

Python - it does not have an operator, but instead a method (`isinstance()`). You can subclass multiple classes or you can even override `__class__()` and return another classes (although it's not recommended, use duck typing when possible instead), but you can't choose whether your class is of type dynamically (you cannot get the `isinstance()` parameter and decide if it's matches you by some criteria).

JS - from ES6 (or something above) has the opposite feature: you can "this value is of my class' type" (`Symbol.hasInstance`), but you can't say "I'm (the value) an instance of this class".

**Comment by mhermier** [comment]
It was added to allow to implement interfaces/protocols. Since we can't
programmatically do it because of the lack of introspection, it allows to
do it manually. So if we expected something to act as a 'Duck', any object
can be be queried using 'is' to see if it act as a 'Duck' and 'quack' even
if it is a 'RubberDuck' that inherit from 'Toy' instead of 'Animal'.

**Comment by ChayimFriedman2** [comment]
Wow. That is really misusing for me. You have to either call `isDuck()` or, for better, `Fiber.try()` calling `quack()`. And I do think we need a way to get a method (in my head I have an API like:
```wren
import "meta" for Meta
System(Meta.getMethod(System, "print")) // null - no method `System.print`
var print = Meta.getMethod(System, "print(_)") // `Fn` wrapper around `System.print(_)`
print.call("This is an indirect call to `System.print(_)`") //> This is an indirect call to `System.print(_)`
```
- what do you think about that, btw?)

**Comment by mhermier** [comment]
You can't add an 'isDuck()' after the fact, if you are (ab)using 3rd party
code.
The example is completely made up. If one take the effort to answer to
'String' interface it is expected to be implemented enough so it is
working, contrary to example that show: wrong stuff is passed and it
doesn't work.

Sure in an ideal world it should be a final operator, but there are case
you want to answer to an interface, but that doesn't need to be fully
implemented to do a working program, and as such users should allow to do
that.

**Comment by ChayimFriedman2** [comment]
> The example is completely made up. If one take the effort to answer to 'String' interface it is expected to be implemented enough so it is working, contrary to example that show: wrong stuff is passed and it doesn't work.
> You can't add an 'isDuck()' after the fact, **_if you are (ab)using 3rd party code._**
You answered yourself. That does not have to be intentional.

**Comment by ChayimFriedman2** [comment]
It also lessen optimization opportunities, if we ever have an optimizing compiler it can use `is` checks to take advantage of type checking. Or not, if the user can overload it.

**Comment by ChayimFriedman2** [comment]
I agree with the need for a meta system, but that seems to me an incorrect solution.

**Comment by ChayimFriedman2** [comment]
And also as I said, the right way IMO is to do `if (Fiber.new { maybeDuck.quack() }.try() == null)`

**Comment by ChayimFriedman2** [comment]
I can implement my suggestion (for `Meta.getBoundMethod()` and `Meta.getUnboundMethod()`) myself, but I'd like to hear feedback. Off topic, I knoe.

**Comment by ruby0x1** [comment]
Please edit your messages to add more, you're generating a lot of notifications unnecessarily. Thanks

**Comment by mhermier** [comment]
Because it is not a static language, that does not have interfaces and
other high level stuff, there is no other proper solution. If reflection
was available there should be an 'implents(_)' method that does kind of
that. The thing is that it would be some kind of a duplication of 'is(_)'.
I agree with what you said it could be an oportunity for optimization...
But that can't really work on a dynamic language.

**Comment by ChayimFriedman2** [comment]
I do think we need to save even the dumb users who want their classes to be strings.
I do not think we need "interfaces like" because we don't have proper support for duck typing. We should have a proper support for duck typing instead 😅

**Comment by ChayimFriedman2** [comment]
Edited the main post to add other languages behavior. You're welcome to add mor.e

**Comment by mhermier** [comment]
Problem is that any more proper solution is usually more expensive and less
expressive, than the cost of protecting ourself from stupid usage.

**Comment by ChayimFriedman2** [comment]
Why? Quite the opposite: instead of trying fight against the lack of duck typing, let's add it!

**Comment by ChayimFriedman2** [comment]
I re-thought about it, and you're partially right. But the current approach isn't good.

In the current method, you write a method that _doesn't have any knowledge of your type_. The only type `String.replace(from, to)` knows is `String`. The fact that you're able to break it using _a method that doesn't refer to it, not explicitly nor implicitly_, is a design flaw. This is exactly the case where two unrelated pieces of software breaks when they're connected, which lead to endless debugging in a code that you haven't written. As long as we deepen the dependency graph, with more and more nodes between the methods, it becomes harder to identify the source of the problem. It's almost not possible to find the source of a bug that only occurs when you combine a certain drawing library with a certain JSON parsing library, while each one itself work fine.

Indeed, we need a way to customize `is` behavior. But instead we need to do that in a manner that allows you (the programmer of `String.replace()`, in our example), to know exactly what will match the condition `is String`.

For this, JS behavior is the best. Let's think about it: how do you define "a string"? a something that is an instance of the `String` class. But how do you define "a duck"? A something that can quack. So, the thing that define the `is` relation is the something we test against (`String` or `Duck`), not the something we test.

So I came to conclusion that we need to reverse the meaning of the `is` method. Instead of `x is y` being translated to `x.is(y)`, we'll translate it to `y.is(x)`. The name of the method is confusing but this is how Wren overload operators, by their name.

This way, `is String` will never get broken, because the `String.is()` operator is the same as `Object.is()`, which tests for instance of class/subclass. But if we want to create our `Duck` type, we can define it (in a very simple manner that just tests against a list of known classes, and will also break if someone for some strange reason overrides the `type` property. Ugh. Maybe we need a method `Object.getType(_)`?):
```wren
class RubberDuck is Toy {}
class RealDuck is Animal {} // Yes, the name is ugly. I didn't want to think about naming in this toy (pun!) example

duckTypes = [RubberDuck, RealDuck]
class Duck {
  // No constructor - this is an interface

  static is_(obj, type) {
    // A reimplementation of `Object.is(class)` for if one of the ducks overrides `is`
    var t = obj.type
    while (t != type && t != null) t = t.supertype
    return t == type
  }

  static is(instance) { // static because we do `is Duck` and not `is <instance of Duck>`
    return duckTypes.any {|duckType| is_(instance, duckType) }
  }
}
```

**Comment by mhermier** [comment]
I think what you are ultimately looking for is guarantee/safety by trying
to reverse the check, so the user can't mess up the check and raise an
argument of potential debuging hell. But it is the contrary, look at the
trace it blame your user class, and even if it was not, the situation will
rapidly evolve to what was passed, exposing user code overloading `is(_)`
operator.

Imagine a situation where I give/provide/maintain a library. What your
solution implies is that I have to know/alter the library each time a user
pop-up asking me to support its user class. Ultimately what your solution
implies that suddenly I have to be aware of the user class and guarantee
that it is working properly because I acknowledged the user code existance.
What you end up doing, at the end of the day, is adding a methods to let
user adds their class to a table like in your example, because I don't want
to deal with importing order or import external user class that may or not
be there. And what you did is simply creating the same situation, where the
user can advert that your `RubberDucky` can `qwack()`, but I have to do
this for every class I provide because I don't know when a user will pop-up
requiring me to mimic one of my class.

What the current situation does is simply revert the situation, by letting
the object manage what it adverts. Suddenly I don't have to know about the
user class, have to checks for its existence or have to test that it works
correctly with user code and maintain compatibility with user code...

**Comment by ChayimFriedman2** [comment]
You're right that we'll end up with creating a method to register my class or even dynamically query, just like the current behavior. However, you're missing an important point: this is fairly explicit. When I test for `is Duck`, I know that every class that claims to be a duck will pass the check. But when I test for `is String`, I hope that only `String` instances will pass the check. Allowing other classes to pass it may break my code accidentally.

By delegating the responsibility for the check to the class we test against, we make sure that the one who perform the test can know its meaning. It _does_ depend on `Duck`, and so it should know its behavior. It _does not_ depend on your class, and so it does not (and should not) know its behavior.

**Comment by mhermier** [comment]
The point you insist on in based on knowledge based on statically typed
language. Dynamic typed language don't require you to implement fully an
interface/mixin, meaning as long as it work why would I care writing stuff
that will not be used anyway.

And at the end of the day, why a class would know better how to test that
the user class is correct? The contract is as simple as "I advertise that I
can be a `Duck` and I provide enough support so that it works". It is the
same contract as implementing an inteface/mixin by advertising it in the
class declaration, at the exception that we are not forced to implement
every virtual.

What you are trying to do is enforce a chain of trust, because the class
*knows* better what user objects it can accept, but in dynamic language it
has no real meaning.

**Comment by ChayimFriedman2** [comment]
In dynamic languages we don't want `is` checks. I understand now what you say, and will close the issue, but this is still not a solution. A full solution is only "real" duck typing, which although Wren can partially achieve through `Fiber.try()`, it cannot fully get it for now. We need a mechanism for this.

**Comment by mhermier** [comment]
You closed it a little but fast I think. What you wanted is to test for
strong inheritance guarantee. And I agree, there might be situation were it
might be required like accessing private data or handing foreign classes...
And I agree such feature can be needed, but the point of my explanations
was that it was important not to mix those very tight notions. If you can
provide a concrete example/test case were such guarantee is required, we
can discuss for solutions. I mean this is the default behavior of `is`
implemented by `Object`, so it can be as easy a duplicating the method call
and forbid overlords, witch should be a 2 liner.

**Comment by ChayimFriedman2** [comment]
I don't understand your point, sorry.

**Comment by mhermier** [comment]
I mean the behavior you wanted should not be the general case, but that
doesn't mean it is not a desired feature for some cases.

**Comment by ChayimFriedman2** [comment]
I did say that I think the built-ins should generally use that, but that doesn't mean others have too.
