### ISSUE TITLE
[Feature request] Shell scripting

### ISSUE THREAD

**Issue by natew** [wren-lang/wren#935]
With the advent of https://github.com/jart/cosmopolitan/issues/104 I think there's room for wren to be an awesome little shell script replacement.

What I'd think would be pretty essential would be to get the syntax and compatibility to be great for running shell scripts. Basically: executing in shell, piping output between things, and handling sub-processes.

Just opening as an idea, feel free to close.

**Comment by alisonatwork** [comment]
I think you might be looking for the https://github.com/wren-lang/wren-cli command-line interpreter. This defines a `Stdin` and `Stdout` object. I haven't gotten that compiling under Cosmopolitan libc just yet, because it has a libuv dependency which might not be easy to port. However, you could write a smaller interpreter than `wren_cli` which just handles stdin and stdout without any snazzy functionality. Something like the `wren_test` tool shows the basics of how to bootstrap a VM and run a script on it.

**Comment by ruby0x1** [comment]
yea @alisonatwork is correct! The language is made to embedded, so any of that exists at the host level. The cli project is one such host, although relatively minimal. There's [another example for the smallest embed here](https://wren.io/embedding/#a-complete-example). 

I've been following the Cosmopolitan discussions so if you manage to get it running let us know.

**Comment by natew** [comment]
I was referring more to having language/library improvements to make wren suitable for shell-style scripting. In effect, as a bash replacement.

**Comment by ruby0x1** [comment]
> executing in shell, piping output between things, and handling sub-processes

none of this can be provided at the language level, by design. Wren is designed to embedded, to be minimal, and that won't be changing. 

I consider the language to already be suitable for shell-style scripting, at the language level, but there is no way the language can provide anything host or platform specific. So if you have _language_ specific suggestions feel free, but these are not language level and can never be provided by Wren without a host, as intended :)

**Comment by natew** [comment]
Other languages handle this, but I get the point about being small, thanks for taking the time to answer!
