### ISSUE TITLE
What's the difference between fiber and generator?

### ISSUE THREAD

**Issue by yisar** [wren-lang/wren#938]
I don't know if there is a clear difference between them.
I think Wren's current coroutine is more like a generator than a fiber?

**Comment by ChayimFriedman2** [comment]
Simply speaking, generators (or "stackless coroutines") can only yield back to the calling function, while fibers (or "stackful coroutines") can yield back to the point that we created them.

Take this JS code as an example:
```js
function* generator() {
  yield;
}
function f() {
    generator();
}
f();
console.log('After calling generator()');
```
The message will be printed, because although the generator yielded and was not resumed this only affects the calling function.

In contrast, with Wren:
```wren
var generator = Fn.new {
  Fiber.yield()
}
var f = Fn.new {
  generator.call()
}
f.call()
System.print("After calling generator()")
```
This will _not_ print the message, because the yield suspend the whole coroutine. If you want it to be printed, you need to create a new fiber:
```wren
var generator = Fn.new {
  Fiber.yield()
}
var f = Fn.new {
  generator.call()
}
Fiber.new { f.call() }.call()
System.print("After calling generator()")
```

**Comment by yisar** [comment]
@ChayimFriedman2 Great, I understand! Thanks!
