### ISSUE TITLE
[RFC] Make 0 falsy

### ISSUE THREAD

**Issue by cxw42** [wren-lang/wren#991]
(Forked off @PureFox48's https://github.com/wren-lang/wren/pull/987#issuecomment-826284806 for visibility)

[At present](https://wren.io/control-flow.html#truth),

> ... 0, empty strings, and empty collections are all considered “true” values.

This proposal is to change +0 and -0 to be falsy.  Per @mhermier's https://github.com/wren-lang/wren/pull/987#issuecomment-826361383, that is pretty easy to do.

This change would reduce the surprise for programmers coming from other languages --- falsy zero is the case in at least the C- and Perl-family languages, and in [PHP](https://www.php.net/manual/en/language.types.boolean.php#language.types.boolean.casting) (just to pick another random example :) ).

**Comment by ChayimFriedman2** [comment]
This was a deliberate design choice, and a meaningful one. BTW, [Lua does the same](https://www.lua.org/pil/2.2.html). And changing it would break existing code.

As for "why", think about default values, for example:
```wren
speed = speed || 5
```
Code like this is common in JS, and programmers must be aware that if 0 is a valid value we should not use it (this is why ES2020 introduced `??`).

**Comment by mhermier** [comment]
Well, there are pros and cons. 0 being equivalent to false is a mathematical fact.
While I understand the example, it is a pro/cons situation and sometimes you also want 0 to trigger the default.
And from my small perspective, I would be more comfortable using a `??` that would popup in search, than looking for a random `||` that was meant to be default value... The argument is not completely fair, since the other behavior would still requires `||`, but at least we can triage some of the uses.

**Comment by PureFox48** [comment]
Having re-read all the discussions about this, I'm coming to the (reluctant) conclusion that the `truthy/falsy` rules should be left as they are. A deliberate design decision was made at the time for good reasons and I think we should honor that particularly as changing them now would not be backwards compatible.

I still see no good reason why we shouldn't introduce `Bool.toNum` and `Num.toBool` which treat `0` as false. Sure, it may be confusing (some explanation in the docs would be needed) but it would allow us to have some cake - and eat it too!

**Comment by ChayimFriedman2** [comment]
I just don't see strong enough evidence to include them in the core. But it's fine to think otherwise 😃

**Comment by PureFox48** [comment]
They're certainly useful if you're translating code from other languages which treat `0` as false and anything else as `true`, which is probably a common activity.

Also they're simple to implement so they're going to have minimal impact on the size of the core.

**Comment by ChayimFriedman2** [comment]
I don't see use cases, even if you translate.

**Comment by PureFox48** [comment]
All I can say is that I wrote my own `btoi` and `itob` methods some time ago and I've found myself using them quite a lot.

**Comment by ChayimFriedman2** [comment]
Can you give an example where?

**Comment by mhermier** [comment]
Regardless of that change, if toBool as to be added, I don't want
surprises, and it must fallow falsy. If you want another behavior, you can
always use an external castor function.

**Comment by PureFox48** [comment]
> Can you give an example where?

Well, the attraction for me is that they allow you to translate code quickly without needing to think too much about it. To take the simplest of examples, suppose you're translating from C and you come across something like this:

```C
while (a) { // blah }
```
where `a` is an `int` variable.

With the proposed new conversion methods in place, you could translate this immediately as:

```javascript
while (a.toBool) { // blah }
```
Otherwise, you have to think what exactly does `a` mean in this context before probably translating as `a != 0` and perhaps having a significant chance of getting it wrong.

Also I have to use a static method for this (`Conv.itob(a)`) at present because I can't inherit from `Num`. If these methods were in core, then they would be instance methods which is obviously much nicer.

Now, if as @mhermier is saying, these methods had to follow the `truthy/falsy` rules, then there would be no point in having them. I'll just stick to using my own methods and others, who support this change, will probably do the same.

**Comment by ChayimFriedman2** [comment]
If `a` is really a boolean but was an integer because of language limitations, just make it an integer.

If it is an integer, `!= 0` makes meaning clearer.

I don't take "easier translation" as an argument; you have to audit it manually either way.

**Comment by PureFox48** [comment]
Well, I think we'll just have to agree to disagree on the utility of these methods.

I see little chance that they'll be added in any case.

**Comment by PureFox48** [comment]
Incidentally, it's a pity that there isn't some way of adding instance methods to the built-in classes without the need for inheritance.

However, this would probably mean adding something like `extension methods` in C# to Wren which would probably open up a can of worms.

**Comment by mhermier** [comment]
The other *common* usage of `0` is `true` has to do with iterators. The idea was to rely sentinel iterator behavior (conversion to bool), instead of their identity (equality comparison). I think it is a conceptual bug.

**Comment by clsource** [comment]
I found myself coding something in JS and it was annoying to know that it failed because it considered `0` as false.

```js
// I had to do something like this
if (typeof result === "number") {
   return result
}

// instead of a simpler
if (result) {
  return result
}
```

So in my opinion Wren should be more like Wren and less than JS 👍

**Comment by mhermier** [comment]
Well your example is biased, I found the first one to be more safe than second one.

**Comment by ChayimFriedman2** [comment]
I prefer `if (result !== null)` (or `undefined`), but I do think using `||` for default values is valuable.

**Comment by mhermier** [comment]
The real problem is that it all boils down to what is a correct default value, and how to represent it. Sometimes it is better to represent it with `0`, sometimes we need `0` to be valid, it is a subjective point of view based on usage.
The fact that `0` and `false` are both unique zeros of their respective algebras, and we can make a surjection from numbers to bool, with a unique transformation from `0` to `false` and all other values resulting to `true`, is always possible. So it only depends on adopting or not that surjection.

If we don't get to a consensus about using `0` to implicit falsy, then the castor method for the surjection should be named differently than `toBool` (and so does `toNum`) so it does not interfere with the wren falsy logic, and don't make a deviation in the meaning of `Bool` in the language.

**Comment by cxw42** [comment]
Random responses/thoughts:
- For default values, `a=a||default` works fine if `a` starts out as `null`, regardless of whether 0 is truthy.
- This originally came up in the context of bool->num.  With 0 truthy, we can't round-trip bool->num->bool while preserving truthiness, which I personally think is a footgun.
- If 0 stayed truthy, alternative names could be Bool.to01() or Bool.step() (like the GLSL step() with the edge at 0)

**Comment by mhermier** [comment]
I'm trying to mitigate the issue on my branch by generalizing `toBool` to be the source of truth, so it can be user defined and so it is easy to add `Num.toBool`. I can say the naive implementation is pretty bad in benchmarks (~25% loss on the worse test string_equals). I have to test with a dedicated vm opcode like `OPCODE_TO_BOOL`, that would perform the call only when necessary to see if I can reduce the impact.

**Comment by ChayimFriedman2** [comment]
> For default values, `a=a||default` works fine if `a` starts out as `null`, regardless of whether 0 is truthy.

The problem arises when `a` is 0.

**Comment by clsource** [comment]
I think one way of solving this without much fuzz is adding a new method to numbers

- `isTrue`: Return true if number is not false, not null and not 0

```js
0.isTrue // false
```

**Comment by mhermier** [comment]
Same fuzz that `toBool`, `True` can be a singleton class of `true`. Don't have particular points against `Bool.to01` or `Bool.step` other than finding it not well named. I was thinking about `toCBool` `toCNum`... dunno if it makes sense...

**Comment by clsource** [comment]
Ok how about this. A static method in `Num` that enables `0` as false explicitly.

`Num.setZeroAsFalse()`

now every comparison of zero can consider that flag to determine if the value is true or false.

**Comment by mhermier** [comment]
While it would solve the issue at global scale, it is not realistic, it means you have to test libraries based on both modes, and/or have to enable it per code sections, which is even more trouble.

**Comment by mhermier** [comment]
One idea would be `Object.isZero` and it would allow to answer to a zero of your type domain, and would not conflict with `Null` or `0`...

**Comment by clsource** [comment]
Ok another idea.

Lets have a new type of 0. One that evaluates to false when using it in comparisons.

`Num.empty`

```js
class NumEmpty {
  construct new() {}
  toNum { 0 }
  toString { toNum.toString )
}

class Num {
  static empty (
     ___empty = (___empty == null) ? NumEmpty.new() : ___empty
     return __empty
   }
}
```

Now if you must deliver a result where `0` is considered false you can return an empty value.

```js

var func = Fn.new {
  // operations
  if (result > 0) {
    return result
  }
  return Num.empty // the value is 0 but is not true when using in comparisons
}
```

I quite dont know if you can override comparisons in a class. Can they?

**Comment by mhermier** [comment]
If we go that route, this is basically a `(Null)Optional`.

Yes there are override-able.

**Comment by BenStigsen** [comment]
The `Object.isTrue` or `Num.toBool` and `Bool.toNum` seems best to me.

**Comment by clsource** [comment]
> If we go that route, this is basically a `(Null)Optional`.
> 
> Yes they are override-able (but `&&` and `||` are not).

Maybe this can be a new RFC to allow them be override-able?

> The `Object.isTrue` or `Num.toBool` and `Bool.toNum` seems best to me.
> 
> EDIT: Perhaps `Object.toBool` would be better than `isTrue`

Agree

**Comment by mhermier** [comment]
@clsource No they can't be overloaded because of the short-circuiting.

@BenStigsen They would be the best, if they didn't make it confusing with the notion of truth used in execution flow control. One could think that `toBool` is the way to overload the notion of truth in wren, and allowing it now, would forbid us to use it in the future making things even more confusing. (On my local branch I use it because I changed the notion of truth, to use an implicit `toBool` as the source of truth, and the current issue is as easy as adding `Num.toBool` in `core`, but it is costly in performance)

**Comment by PureFox48** [comment]
I quite like @mhermier’s idea of using `Num.toCBool` and `Bool.toCNum` for these methods.

These names would make it clear that we’re taking about C’s notion of truth rather than Wren’s.

**Comment by clsource** [comment]
In that case 

- `Num.fromBool(_)`: Would treat false, null or 0 as `0` and any other value as `1`
- `Bool.fromNum(_)`: Would treat null, false or 0 as `false`. Otherwise `true`.

**Comment by ChayimFriedman2** [comment]
Now, the question it: should we place them on `Object` or `Num`? I think that if they reject non-`Num` (e.g. `null`) then place them on `Num`, otherwise on `Object`.

**Comment by mhermier** [comment]
@clsource same issue in reverse, the function naming suggest it should follow the wren notion of truth. It is just instead of using a castor function you are using a constructor function.

If we resolve the naming issue, I think it is better to be in `Num` and `Bool` and non static. It allow to make a generic method protocol later, requiring only to add the `Object` implementation.

**Comment by clsource** [comment]
Ok how about

- `toBool`: Normal Wren Bools. 0 is true
- `toBoolStrict` Stricter Wren Bools. 0 is false

**Comment by mhermier** [comment]
Well I proposed `toCBool` for that earlier. The question would be what is a good name that would satisfy every one. `toBoolStrict` is not bad in the sense it not `toBool`, but does not feel good (at least to me). I wonder if math or C as a name for that feature, in type theory or something ?

**Comment by Orcolom** [comment]
Maybe we can refer to electronic terms like toBoolSignal. Strict could work.  Don't think we should use CBool

**Comment by mhermier** [comment]
I have no idea, it is a problem of naming, the biggest problem in computer science.

**Comment by clsource** [comment]
Maybe related to https://en.wikipedia.org/wiki/De_Morgan%27s_laws

- `toBool`: 0 is true
- `toDemorgan`: negates 0 (0 is false)
-

**Comment by mhermier** [comment]
`toIntegralBool` ? read on some C++ related question that the conversion is due to the fact that in C++ bool is an integral/integer number.

**Comment by clsource** [comment]
Personally I think that naming `toCBool` is a fine option. But it lacks generality since you have to know what is `C` first and then understand how a boolean works in `C`. It ties up Wren too much to C in my opinion.

persoanlly I will stick to `Demorgan` since it means a complement to normal `Bool` 👍 or until a better option appears.

**Comment by cxw42** [comment]
How about `Bool.to01()` and `static Bool.from01(_)`?  I think that's fairly descriptive.  

Or we could call 0-falsy values `George` after George Boole :)

**Comment by BenStigsen** [comment]
I'm not a fan of `Demorgan` at all. I think `Bool.toNum` is better than `Bool.to01` . `Bool.toNum` reads more clearly and easily, as well as being consistent with the `Number` type.

**Comment by mhermier** [comment]
As per truthy definition `Bool.toNum` does not really have sense, since it would be defined for `true`, and could be any value.

**Comment by BenStigsen** [comment]
Other languages simply convert `true` to a `1`.
`Bool.toNum` sounds and reads more pleasantly. It also describes what is happening, that a boolean is converted to a number.

**Comment by cxw42** [comment]
@BenStigsen I agree that `toNum` would be preferable.  However, I also agree with @mhermier 's https://github.com/wren-lang/wren/issues/991#issuecomment-829634412 that `toNum` would be confusing since 0 == true in Wren currently.  As far as I can tell from this discussion, there's not a strong reason to change that.  That's why we're looking for alternative names.  Do you have a second choice you could propose?

**Comment by sukhchainn** [comment]
I think there should be a toNum function in Num Class. because at times when a dev is writing code for mathematical calculation and a gotcha like 0==true happens then he knows which Class to look helpful functions for. This is especially true for new comers like me.

**Comment by PureFox48** [comment]
Well, having read the whole thread again from scratch, I've concluded that `Bool.toCNum` and `Num.toCBool` are the best suggestions so far.

They're concise, reasonably self-explanatory and distinguish C truth from Wren truth.

Most embedders are going to have at least some knowledge of C to be able to understand the API docs in the first place and, even if they haven't, the docs should make the distinction clear. Here's an attempt at the latter:

**Num.toCBool**

Converts this number to a Bool using the C language's notion of truth i.e. `0` corresponds to `false` and any other number (including NaN) to `true`.

Note that this differs from Wren's notion of truth where every number (including `0`) is considered to be `true`.

**Bool.toCNum**

Converts this value to a Num using the C language's notion of truth i.e. `false` corresponds to `0` and `true` to 1.

Note that this differs from Wren's notion of truth where every number (including `0`) is considered to be `true`.

**Comment by mhermier** [comment]
@PureFox48 Probably not the best name I ever suggested, but this sums up pretty well what I thought when I suggested them the first time.

Documentation is probably to specific for `Num.toCBool` about NaN values. I suggest says that it to says that it conform to C `number != 0`, or `!!number` (even if that is undefined behavior of some sort). It would also solve the issue where `-0` could be considered to be `true` according to the definition.

**Comment by PureFox48** [comment]
I tried NaN, positive and negative infinity in GCC before my previous post and they all returned `true`.

Although I'm no expert, this appears to conform to the C99 standard.

In 6.2.5.21 it says:
"Arthmetic types and pointer types are collectively called `scalar` types."

and in 6.3.1.2 it says:
When any `scalar` value is converted to _Bool, the result is 0 if the value compares equal to 0; otherwise the value is 1."

So I don't think it does any harm to be explicit about NaN (and infinities for that matter) though I agree that we need to mention that `-0` (which in C compares equal to `0`) corresponds to `false` as well:

**Num.toCBool**

Converts this number to a Bool using the C99 language's notion of truth i.e. `0` (or `-0`) corresponds to `false` and any other number (including ±infinity and NaN) to `true`.

Note that this differs from Wren's notion of truth where every number (including `±0`) is considered to be `true`.

**Bool.toCNum**

Converts this value to a Num using the C99 language's notion of truth i.e. `false` corresponds to `0` and `true` to 1.

Note that this differs from Wren's notion of truth where every number (including `±0`)  ) is considered to be `true`

**Comment by mhermier** [comment]
At some minor editing this is good then.

**Comment by Orcolom** [comment]
Seems like we agreed that 0 wont become fasly and reached somewhat a consensus on https://github.com/wren-lang/wren/pull/987 should be. close this?

**Comment by mhermier** [comment]
I think we should way for the push request to be finalized before we close both.

**Comment by mhermier** [comment]
Who want to do the patch? It is trivial enough to be make some experience on the VM, or if necessary, I should be able to do it in less than half hour.

**Comment by cxw42** [comment]
I just looked at this and #987 again, and I think that PR is good.  Closing this to keep the issue list tidy --- let me know if you have any concerns!

**Comment by filipworksdev** [comment]
Hello. As an outsider to this conversation I think this is a weird design choice. I understand there are practical reasons for this  but I have never used `while(0)` or `if ("")` to mean true. I have seen a lot of downvotes from core devs on anyone disagreeing so I'm not trying to disagree I am a complete outsider coming to this language and I find it unusable in this state. I have to think completely backwards that I'm used to. I was working on embedding Wren into my game engine fork project but I realize it might not be compatible with the current implemented engine logic. I would need to flip the Falsy values in Wren vm. Is there a PR or fork implemented with 0 flipped to False so I can use that as a basis for my modifications? Thank you.

**Comment by mhermier** [comment]
I have a patch set for that feature in my personal git. I can set-up a
branch for it, but I don't want to maintain it as a separated feature
branch.

**Comment by filipworksdev** [comment]
Hi @mhermier  thank you for the reply. Would it be possible to access these patches? You would not need to maintain a separate branch. I just need to know what to change since I am completely unfamilair with the vm at this time. Thank you.

**Comment by mhermier** [comment]
It is a little bit complicated to extract these patch cleanly on my change set because it is tight to a `Object.toBool` change that I have.
But basically you only have to edit `wrenIsFalsyValue` so that it also test `(IS_NUM(value) && (AS_NUM(value) == 0.0))`. After that you have to fix a little the core library (easily spotted by the test suite), because some iterator logic broke (because of minor issues where logic rely on falsy values instead of testing against `null` (begin of iterable) and `false` (end of iterable)).
